"""
MCP Server Code Generation Engine - Sprint 6.0
Generates production-ready TypeScript and Python MCP server code
"""
from typing import Dict, List, Optional
from dataclasses import dataclass
from enum import Enum


class AuthType(str, Enum):
    """Authentication types supported"""
    NONE = "none"
    API_KEY = "api_key"
    OAUTH2 = "oauth2"
    CUSTOM = "custom"


@dataclass
class ToolParameter:
    """Parameter definition for a tool"""
    name: str
    type: str  # string, number, boolean, array, object
    description: str
    required: bool = True
    default: Optional[str] = None


@dataclass
class ToolDefinition:
    """Definition of an MCP tool"""
    name: str
    description: str
    method: str  # GET, POST, PUT, DELETE
    path: str  # API endpoint path
    parameters: List[ToolParameter]
    response_mapping: Dict[str, str]  # Maps response fields to output


class MCPCodeGenerator:
    """Generates MCP server code from specifications"""

    def generate_typescript(
        self,
        server_name: str,
        base_url: str,
        auth_type: AuthType,
        auth_config: Dict,
        tools: List[ToolDefinition]
    ) -> str:
        """
        Generate TypeScript MCP server code

        Returns complete TypeScript code as string
        """
        code = f'''/**
 * {server_name} MCP Server
 * Generated by Binary-Blender Binary-Blender Orchestrator
 *
 * This MCP server wraps the {base_url} API
 */

import {{ Server }} from "@modelcontextprotocol/sdk/server/index.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{
  ListToolsRequestSchema,
  CallToolRequestSchema,
  ErrorCode,
  McpError,
}} from "@modelcontextprotocol/sdk/types.js";

const API_BASE_URL = "{base_url}";
'''

        # Add auth configuration
        if auth_type == AuthType.API_KEY:
            code += f'''
const API_KEY = process.env.{server_name.upper()}_API_KEY || "";

if (!API_KEY) {{
  console.error("Error: {server_name.upper()}_API_KEY environment variable is required");
  process.exit(1);
}}

const AUTH_HEADERS = {{
  "{auth_config.get('header_name', 'Authorization')}": `{auth_config.get('header_prefix', 'Bearer ')}${{API_KEY}}`
}};
'''
        else:
            code += '''
const AUTH_HEADERS = {};
'''

        # Add server class
        code += f'''
class {server_name.replace("-", "").replace("_", "")}Server {{
  private server: Server;

  constructor() {{
    this.server = new Server(
      {{
        name: "{server_name}",
        version: "1.0.0",
      }},
      {{
        capabilities: {{
          tools: {{}},
        }},
      }}
    );

    this.setupToolHandlers();

    // Error handling
    this.server.onerror = (error) => console.error("[MCP Error]", error);
    process.on("SIGINT", async () => {{
      await this.server.close();
      process.exit(0);
    }});
  }}

  private setupToolHandlers() {{
    this.server.setRequestHandler(ListToolsRequestSchema, async () => ({{
      tools: [
'''

        # Add tool definitions
        for tool in tools:
            params_schema = self._generate_ts_params_schema(tool.parameters)
            code += f'''
        {{
          name: "{tool.name}",
          description: "{tool.description}",
          inputSchema: {params_schema}
        }},
'''

        code += '''
      ],
    }));

    this.server.setRequestHandler(CallToolRequestSchema, async (request) => {
      switch (request.params.name) {
'''

        # Add tool implementations
        for tool in tools:
            code += f'''
        case "{tool.name}":
          return await this.{tool.name}(request.params.arguments ?? {{}});
'''

        code += '''
        default:
          throw new McpError(
            ErrorCode.MethodNotFound,
            `Unknown tool: ${request.params.name}`
          );
      }
    });
  }
'''

        # Add tool method implementations
        for tool in tools:
            code += self._generate_ts_tool_method(tool)

        # Add run method
        code += '''
  async run() {
    const transport = new StdioServerTransport();
    await this.server.connect(transport);
    console.error("MCP server running on stdio");
  }
}

const server = new {server_name.replace("-", "").replace("_", "")}Server();
server.run().catch(console.error);
'''

        return code

    def _generate_ts_params_schema(self, parameters: List[ToolParameter]) -> str:
        """Generate TypeScript JSON schema for parameters"""
        required = [p.name for p in parameters if p.required]

        properties = {}
        for param in parameters:
            prop = {
                "type": param.type,
                "description": param.description
            }
            if param.default:
                prop["default"] = param.default
            properties[param.name] = prop

        schema = {
            "type": "object",
            "properties": properties,
            "required": required
        }

        import json
        return json.dumps(schema, indent=10)

    def _generate_ts_tool_method(self, tool: ToolDefinition) -> str:
        """Generate TypeScript method for a tool"""
        method = f'''
  private async {tool.name}(args: any): Promise<any> {{
    try {{
      // Validate required parameters
'''

        for param in tool.parameters:
            if param.required:
                method += f'''
      if (!args.{param.name}) {{
        throw new McpError(
          ErrorCode.InvalidParams,
          "Missing required parameter: {param.name}"
        );
      }}
'''

        # Build request URL
        if tool.method == "GET":
            # Add query parameters to URL
            method += f'''
      // Build query string
      const params = new URLSearchParams();
'''
            for param in tool.parameters:
                method += f'''
      if (args.{param.name}) params.append("{param.name}", args.{param.name});
'''
            method += f'''
      const url = `${{API_BASE_URL}}{tool.path}?${{params.toString()}}`;

      const response = await fetch(url, {{
        method: "{tool.method}",
        headers: {{
          ...AUTH_HEADERS,
        }},
      }});
'''
        else:
            # POST/PUT/DELETE with body
            method += f'''
      const url = `${{API_BASE_URL}}{tool.path}`;

      const response = await fetch(url, {{
        method: "{tool.method}",
        headers: {{
          ...AUTH_HEADERS,
          "Content-Type": "application/json",
        }},
        body: JSON.stringify(args),
      }});
'''

        # Handle response
        method += '''
      if (!response.ok) {
        throw new McpError(
          ErrorCode.InternalError,
          `API request failed: ${response.statusText}`
        );
      }

      const data = await response.json();

      // Map response to MCP format
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(data, null, 2)
          }
        ]
      };
    } catch (error) {
      if (error instanceof McpError) throw error;

      throw new McpError(
        ErrorCode.InternalError,
        `Tool execution failed: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }
'''
        return method

    def generate_python(
        self,
        server_name: str,
        base_url: str,
        auth_type: AuthType,
        auth_config: Dict,
        tools: List[ToolDefinition]
    ) -> str:
        """
        Generate Python MCP server code

        Returns complete Python code as string
        """
        code = f'''"""
{server_name} MCP Server
Generated by Binary-Blender Binary-Blender Orchestrator

This MCP server wraps the {base_url} API
"""
import asyncio
import os
import json
from typing import Any, Dict, List
import httpx
from mcp.server.models import InitializationOptions
from mcp.server import NotificationOptions, Server
from mcp.server.stdio import stdio_server
from mcp import types

API_BASE_URL = "{base_url}"
'''

        # Add auth configuration
        if auth_type == AuthType.API_KEY:
            code += f'''
API_KEY = os.getenv("{server_name.upper()}_API_KEY", "")

if not API_KEY:
    raise ValueError("{server_name.upper()}_API_KEY environment variable is required")

AUTH_HEADERS = {{
    "{auth_config.get('header_name', 'Authorization')}": f"{auth_config.get('header_prefix', 'Bearer ')}{{API_KEY}}"
}}
'''
        else:
            code += '''
AUTH_HEADERS = {}
'''

        # Create server instance
        code += f'''
server = Server("{server_name}")

@server.list_tools()
async def handle_list_tools() -> List[types.Tool]:
    """List available tools"""
    return [
'''

        # Add tool definitions
        for tool in tools:
            params_schema = self._generate_py_params_schema(tool.parameters)
            code += f'''
        types.Tool(
            name="{tool.name}",
            description="{tool.description}",
            inputSchema={params_schema}
        ),
'''

        code += '''
    ]


@server.call_tool()
async def handle_call_tool(
    name: str, arguments: Dict[str, Any] | None
) -> List[types.TextContent]:
    """Execute a tool"""
    if arguments is None:
        arguments = {}

'''

        # Add tool implementations
        for i, tool in enumerate(tools):
            if_keyword = "if" if i == 0 else "elif"
            code += f'''
    {if_keyword} name == "{tool.name}":
        return await {tool.name}(arguments)
'''

        code += '''
    else:
        raise ValueError(f"Unknown tool: {name}")
'''

        # Add tool functions
        for tool in tools:
            code += self._generate_py_tool_function(tool)

        # Add main
        code += '''

async def main():
    """Run the MCP server"""
    async with stdio_server() as (read_stream, write_stream):
        await server.run(
            read_stream,
            write_stream,
            InitializationOptions(
                server_name="{server_name}",
                server_version="1.0.0",
                capabilities=server.get_capabilities(
                    notification_options=NotificationOptions(),
                    experimental_capabilities={},
                ),
            ),
        )


if __name__ == "__main__":
    asyncio.run(main())
'''

        return code

    def _generate_py_params_schema(self, parameters: List[ToolParameter]) -> str:
        """Generate Python JSON schema for parameters"""
        required = [p.name for p in parameters if p.required]

        properties = {}
        for param in parameters:
            prop = {
                "type": param.type,
                "description": param.description
            }
            if param.default:
                prop["default"] = param.default
            properties[param.name] = prop

        schema = {
            "type": "object",
            "properties": properties,
            "required": required
        }

        import json
        return json.dumps(schema, indent=8)

    def _generate_py_tool_function(self, tool: ToolDefinition) -> str:
        """Generate Python function for a tool"""
        func = f'''

async def {tool.name}(args: Dict[str, Any]) -> List[types.TextContent]:
    """Execute {tool.name} tool"""
    # Validate required parameters
'''

        for param in tool.parameters:
            if param.required:
                func += f'''
    if "{param.name}" not in args:
        raise ValueError("Missing required parameter: {param.name}")
'''

        # Make API request
        if tool.method == "GET":
            func += f'''

    async with httpx.AsyncClient() as client:
        params = {{k: v for k, v in args.items() if v is not None}}
        response = await client.get(
            f"{{API_BASE_URL}}{tool.path}",
            headers=AUTH_HEADERS,
            params=params,
            timeout=30.0
        )
        response.raise_for_status()
        data = response.json()
'''
        else:
            func += f'''

    async with httpx.AsyncClient() as client:
        response = await client.{tool.method.lower()}(
            f"{{API_BASE_URL}}{tool.path}",
            headers={{**AUTH_HEADERS, "Content-Type": "application/json"}},
            json=args,
            timeout=30.0
        )
        response.raise_for_status()
        data = response.json()
'''

        func += '''

    return [
        types.TextContent(
            type="text",
            text=json.dumps(data, indent=2)
        )
    ]
'''

        return func

    def generate_docker_config(self, server_name: str, language: str) -> str:
        """Generate Dockerfile for the MCP server"""
        if language == "typescript":
            return f'''FROM node:20-slim

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --production

# Copy source code
COPY . .

# Build TypeScript
RUN npm run build

# Run server
CMD ["node", "dist/index.js"]
'''
        else:  # Python
            return f'''FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Run server
CMD ["python", "server.py"]
'''

    def generate_readme(
        self,
        server_name: str,
        base_url: str,
        tools: List[ToolDefinition]
    ) -> str:
        """Generate README documentation"""
        readme = f'''# {server_name} MCP Server

MCP server for {base_url} API

Generated by Binary-Blender Binary-Blender Orchestrator

## Installation

### TypeScript
```bash
npm install
npm run build
```

### Python
```bash
pip install -r requirements.txt
```

## Usage

Add to your MCP settings:

```json
{{
  "mcpServers": {{
    "{server_name}": {{
      "command": "node",
      "args": ["path/to/{server_name}/dist/index.js"]
    }}
  }}
}}
```

## Available Tools

'''

        for tool in tools:
            readme += f'''### {tool.name}

**Description:** {tool.description}

**Parameters:**
'''
            for param in tool.parameters:
                required = "**Required**" if param.required else "Optional"
                readme += f"- `{param.name}` ({param.type}) - {param.description} - {required}\n"

            readme += "\n"

        readme += '''
## License

Generated code is provided as-is.
'''

        return readme
