// Generates a complete Axum web server from ENTITY, ACTION, AUTH, TENANT declarations.
// Activated when TARGET.runtime === 'axum'. Produces idiomatic Rust with sqlx + PostgreSQL.

import type { AgiFile, EntityDecl, ActionDecl, FieldDef, AuthDecl, TenantDecl } from '@agicore/parser';

export function generateAxum(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (!ast.target || ast.target.runtime !== 'axum') return files;

  const { entities, actions, auth, tenant, app } = ast;
  const appName = toSnake(app.name);

  files.set('Cargo.toml', buildCargoToml(appName));
  files.set('src/main.rs', buildMainRs(entities, auth, tenant));
  files.set('src/db.rs', buildDbRs());
  files.set('src/error.rs', buildErrorRs());
  files.set('src/middleware/auth.rs', buildAuthMiddleware(auth));
  files.set('src/models/mod.rs', entities.map(e => `pub mod ${toSnake(e.name)};`).join('\n'));
  files.set('src/routes/mod.rs', buildRoutesMod(entities, actions));

  for (const entity of entities) {
    files.set(`src/models/${toSnake(entity.name)}.rs`, buildEntityModel(entity));
    files.set(`src/routes/${toSnake(entity.name)}.rs`, buildEntityRoutes(entity, tenant));
  }

  if (actions.length > 0) {
    files.set('src/routes/actions.rs', buildActionRoutes(actions, auth));
  }

  return files;
}

// ─── Cargo.toml ──────────────────────────────────────────────────────────────

function buildCargoToml(appName: string): string {
  return `[package]
name = "${appName}"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "${appName}"
path = "src/main.rs"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.5", features = ["cors", "trace"] }
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio", "uuid", "chrono", "migrate"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonwebtoken = "9"
uuid = { version = "1", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
anyhow = "1"
thiserror = "1"
`;
}

// ─── main.rs ─────────────────────────────────────────────────────────────────

function buildMainRs(entities: EntityDecl[], _auth: AuthDecl | undefined, _tenant: TenantDecl | undefined): string {
  const routeMerges = entities.map(e =>
    `        .merge(routes::${toSnake(e.name)}::${toSnake(e.name)}_routes())`
  ).join('\n');

  return `// main.rs — generated by Agicore web target
// @agicore-generated — DO NOT EDIT (regenerate via: agicore compile)

mod db;
mod error;
mod middleware;
mod models;
mod routes;

use axum::{Router, middleware as axum_middleware};
use tower_http::cors::{Any, CorsLayer};
use tower_http::trace::TraceLayer;
use tracing_subscriber::{layer::SubscriberExt, util::SubscriberInitExt};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    dotenvy::dotenv().ok();

    tracing_subscriber::registry()
        .with(tracing_subscriber::EnvFilter::try_from_default_env()
            .unwrap_or_else(|_| "info".into()))
        .with(tracing_subscriber::fmt::layer())
        .init();

    let database_url = std::env::var("DATABASE_URL")
        .expect("DATABASE_URL environment variable must be set");

    let pool = db::create_pool(&database_url).await?;

    sqlx::migrate!("./migrations").run(&pool).await?;

    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods(Any)
        .allow_headers(Any);

    let app = build_router(pool)
        .layer(cors)
        .layer(TraceLayer::new_for_http());

    let port = std::env::var("PORT").unwrap_or_else(|_| "3000".to_string());
    let addr = format!("0.0.0.0:{port}");
    tracing::info!("Listening on {addr}");

    let listener = tokio::net::TcpListener::bind(&addr).await?;
    axum::serve(listener, app).await?;
    Ok(())
}

fn build_router(pool: sqlx::PgPool) -> Router {
    let state = db::AppState { pool };
    Router::new()
${routeMerges}
        .with_state(state)
}
`;
}

// ─── db.rs ───────────────────────────────────────────────────────────────────

function buildDbRs(): string {
  return `// db.rs — PostgreSQL connection pool
use sqlx::PgPool;

#[derive(Clone)]
pub struct AppState {
    pub pool: PgPool,
}

pub async fn create_pool(database_url: &str) -> anyhow::Result<PgPool> {
    let pool = PgPool::connect(database_url).await?;
    Ok(pool)
}
`;
}

// ─── error.rs ────────────────────────────────────────────────────────────────

function buildErrorRs(): string {
  return `// error.rs — Unified error type that maps to HTTP responses
use axum::{http::StatusCode, response::{IntoResponse, Response}, Json};
use serde_json::json;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum AppError {
    #[error("Not found")]
    NotFound,
    #[error("Unauthorized")]
    Unauthorized,
    #[error("Forbidden")]
    Forbidden,
    #[error("Validation error: {0}")]
    Validation(String),
    #[error("Database error: {0}")]
    Database(#[from] sqlx::Error),
    #[error("Internal error: {0}")]
    Internal(#[from] anyhow::Error),
}

impl IntoResponse for AppError {
    fn into_response(self) -> Response {
        let (status, message) = match &self {
            AppError::NotFound     => (StatusCode::NOT_FOUND, self.to_string()),
            AppError::Unauthorized => (StatusCode::UNAUTHORIZED, self.to_string()),
            AppError::Forbidden    => (StatusCode::FORBIDDEN, self.to_string()),
            AppError::Validation(m) => (StatusCode::UNPROCESSABLE_ENTITY, m.clone()),
            AppError::Database(_)  => (StatusCode::INTERNAL_SERVER_ERROR, "Database error".into()),
            AppError::Internal(_)  => (StatusCode::INTERNAL_SERVER_ERROR, "Internal error".into()),
        };
        (status, Json(json!({ "error": message }))).into_response()
    }
}
`;
}

// ─── middleware/auth.rs ───────────────────────────────────────────────────────

function buildAuthMiddleware(auth: AuthDecl | undefined): string {
  const expiry = auth?.expiry ?? '8h';
  return `// middleware/auth.rs — JWT extraction and verification
use axum::{
    async_trait,
    extract::FromRequestParts,
    http::{request::Parts, StatusCode},
};
use jsonwebtoken::{decode, DecodingKey, Validation, Algorithm};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuthClaims {
    pub sub: String,
    pub tenant_id: String,
    pub roles: Vec<String>,
    pub exp: usize,
}

#[async_trait]
impl<S> FromRequestParts<S> for AuthClaims
where
    S: Send + Sync,
{
    type Rejection = (StatusCode, &'static str);

    async fn from_request_parts(parts: &mut Parts, _state: &S) -> Result<Self, Self::Rejection> {
        let auth_header = parts
            .headers
            .get("Authorization")
            .and_then(|v| v.to_str().ok())
            .ok_or((StatusCode::UNAUTHORIZED, "Missing Authorization header"))?;

        let token = auth_header
            .strip_prefix("Bearer ")
            .ok_or((StatusCode::UNAUTHORIZED, "Invalid Authorization format"))?;

        let secret = std::env::var("JWT_SECRET")
            .unwrap_or_else(|_| "change-me-in-production".to_string());

        let claims = decode::<AuthClaims>(
            token,
            &DecodingKey::from_secret(secret.as_bytes()),
            &Validation::new(Algorithm::HS256),
        )
        .map_err(|_| (StatusCode::UNAUTHORIZED, "Invalid or expired token"))?
        .claims;

        Ok(claims)
    }
}

pub fn generate_token(sub: &str, tenant_id: &str, roles: &[String]) -> anyhow::Result<String> {
    use jsonwebtoken::{encode, EncodingKey, Header};
    use std::time::{SystemTime, UNIX_EPOCH};

    let expiry_hours: u64 = "${expiry}".trim_end_matches('h').parse().unwrap_or(8);
    let exp = SystemTime::now()
        .duration_since(UNIX_EPOCH)?
        .as_secs() + expiry_hours * 3600;

    let claims = AuthClaims {
        sub: sub.to_string(),
        tenant_id: tenant_id.to_string(),
        roles: roles.to_vec(),
        exp: exp as usize,
    };

    let secret = std::env::var("JWT_SECRET")
        .unwrap_or_else(|_| "change-me-in-production".to_string());

    Ok(encode(
        &Header::default(),
        &claims,
        &EncodingKey::from_secret(secret.as_bytes()),
    )?)
}
`;
}

// ─── routes/mod.rs ───────────────────────────────────────────────────────────

function buildRoutesMod(entities: EntityDecl[], actions: ActionDecl[]): string {
  const mods = [
    ...entities.map(e => `pub mod ${toSnake(e.name)};`),
    ...(actions.length > 0 ? ['pub mod actions;'] : []),
  ].join('\n');
  return mods + '\n';
}

// ─── Per-entity model ────────────────────────────────────────────────────────

function buildEntityModel(entity: EntityDecl): string {
  const name = entity.name;
  const snake = toSnake(name);
  const fields = entity.fields;

  const responseFields = fields.map(f => `    pub ${toSnake(f.name)}: ${rustType(f)},`).join('\n');
  const createFields = fields
    .filter(f => !['id', 'created_at', 'updated_at'].includes(toSnake(f.name)))
    .map(f => `    pub ${toSnake(f.name)}: ${rustTypeInput(f)},`)
    .join('\n');

  return `// models/${snake}.rs — generated by Agicore
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::FromRow)]
pub struct ${name} {
    pub id: Uuid,
${responseFields}
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Deserialize)]
pub struct Create${name} {
${createFields}
}

#[derive(Debug, Deserialize)]
pub struct Update${name} {
${createFields.replace(/: ([^,\n]+),/g, ': Option<$1>,')}
}

#[derive(Debug, Deserialize, Default)]
pub struct ${name}ListParams {
    pub limit: Option<i64>,
    pub offset: Option<i64>,
}
`;
}

// ─── Per-entity routes ───────────────────────────────────────────────────────

function buildEntityRoutes(entity: EntityDecl, tenant: TenantDecl | undefined): string {
  const name = entity.name;
  const snake = toSnake(name);
  const table = snake + 's';
  const crudRaw = entity.crud;
  const crud: string[] = crudRaw === 'full'
    ? ['create', 'read', 'update', 'delete', 'list']
    : (crudRaw as string[]);
  const hasTenant = !!tenant;
  const tenantKey = tenant?.key ?? 'tenant_id';

  const tenantFilter = hasTenant
    ? `WHERE ${tenantKey} = $1`
    : '';
  const tenantParam = hasTenant ? `auth.${tenantKey},` : '';
  const tenantExtract = hasTenant
    ? `\n    auth: crate::middleware::auth::AuthClaims,`
    : '';

  const fields = entity.fields.filter(f => !['id', 'created_at', 'updated_at'].includes(toSnake(f.name)));
  const insertCols = fields.map(f => toSnake(f.name)).join(', ');
  const insertPlaceholders = fields.map((_, i) => `$${i + (hasTenant ? 2 : 1)}`).join(', ');
  const insertParams = fields.map(f => `body.${toSnake(f.name)}`).join(',\n        ');

  const updateSets = fields
    .map((f, i) => `${toSnake(f.name)} = COALESCE($${i + 2}, ${toSnake(f.name)})`)
    .join(', ');

  let handlers = '';

  if (crud.includes('list')) {
    handlers += `
async fn list(
    State(state): State<AppState>,${tenantExtract}
    Query(params): Query<${name}ListParams>,
) -> Result<Json<Vec<${name}>>, AppError> {
    let rows = sqlx::query_as!(
        ${name},
        r#"SELECT id, ${fields.map(f => toSnake(f.name)).join(', ')}, created_at, updated_at
           FROM ${table}
           ${tenantFilter}
           ORDER BY created_at DESC
           LIMIT $${hasTenant ? 2 : 1} OFFSET $${hasTenant ? 3 : 2}"#,
        ${tenantParam}
        params.limit.unwrap_or(50),
        params.offset.unwrap_or(0),
    )
    .fetch_all(&state.pool)
    .await?;
    Ok(Json(rows))
}
`;
  }

  if (crud.includes('read')) {
    handlers += `
async fn get_one(
    State(state): State<AppState>,${tenantExtract}
    Path(id): Path<uuid::Uuid>,
) -> Result<Json<${name}>, AppError> {
    let row = sqlx::query_as!(
        ${name},
        r#"SELECT id, ${fields.map(f => toSnake(f.name)).join(', ')}, created_at, updated_at
           FROM ${table}
           WHERE id = $1${hasTenant ? ` AND ${tenantKey} = $2` : ''}"#,
        id,${hasTenant ? '\n        auth.' + tenantKey + ',' : ''}
    )
    .fetch_optional(&state.pool)
    .await?
    .ok_or(AppError::NotFound)?;
    Ok(Json(row))
}
`;
  }

  if (crud.includes('create')) {
    handlers += `
async fn create(
    State(state): State<AppState>,${tenantExtract}
    Json(body): Json<Create${name}>,
) -> Result<Json<${name}>, AppError> {
    let id = uuid::Uuid::new_v4();
    let row = sqlx::query_as!(
        ${name},
        r#"INSERT INTO ${table} (id, ${insertCols})
           VALUES ($1, ${insertPlaceholders})
           RETURNING id, ${fields.map(f => toSnake(f.name)).join(', ')}, created_at, updated_at"#,
        id,
        ${insertParams},
    )
    .fetch_one(&state.pool)
    .await?;
    Ok(Json(row))
}
`;
  }

  if (crud.includes('update') || crud.includes('edit')) {
    handlers += `
async fn update(
    State(state): State<AppState>,${tenantExtract}
    Path(id): Path<uuid::Uuid>,
    Json(body): Json<Update${name}>,
) -> Result<Json<${name}>, AppError> {
    let row = sqlx::query_as!(
        ${name},
        r#"UPDATE ${table}
           SET ${updateSets}, updated_at = NOW()
           WHERE id = $1${hasTenant ? ` AND ${tenantKey} = $${fields.length + 2}` : ''}
           RETURNING id, ${fields.map(f => toSnake(f.name)).join(', ')}, created_at, updated_at"#,
        id,
        ${fields.map(f => `body.${toSnake(f.name)}`).join(',\n        ')},${hasTenant ? '\n        auth.' + tenantKey + ',' : ''}
    )
    .fetch_optional(&state.pool)
    .await?
    .ok_or(AppError::NotFound)?;
    Ok(Json(row))
}
`;
  }

  if (crud.includes('delete')) {
    handlers += `
async fn remove(
    State(state): State<AppState>,${tenantExtract}
    Path(id): Path<uuid::Uuid>,
) -> Result<StatusCode, AppError> {
    let result = sqlx::query!(
        r#"DELETE FROM ${table} WHERE id = $1${hasTenant ? ` AND ${tenantKey} = $2` : ''}"#,
        id,${hasTenant ? '\n        auth.' + tenantKey + ',' : ''}
    )
    .execute(&state.pool)
    .await?;
    if result.rows_affected() == 0 {
        return Err(AppError::NotFound);
    }
    Ok(StatusCode::NO_CONTENT)
}
`;
  }

  const routeRegistrations = buildRouteRegistrations(snake, crud);

  return `// routes/${snake}.rs — generated by Agicore
use axum::{
    extract::{Path, Query, State},
    http::StatusCode,
    response::Json,
    routing::{delete, get, post, put},
    Router,
};
use crate::{db::AppState, error::AppError, models::${snake}::*};
${handlers}
pub fn ${snake}_routes() -> Router<AppState> {
    Router::new()
        ${routeRegistrations}
}
`;
}

function buildRouteRegistrations(snake: string, crud: string[]): string {
  const lines: string[] = [];
  const listCreate: string[] = [];
  if (crud.includes('list')) listCreate.push('get(list)');
  if (crud.includes('create')) listCreate.push('post(create)');
  if (listCreate.length) {
    lines.push(`.route("/api/${snake}s", ${listCreate.join('.').replace('get(list)post(create)', 'get(list).post(create)')})`);
  }

  const idOps: string[] = [];
  if (crud.includes('read')) idOps.push('get(get_one)');
  if (crud.includes('update') || crud.includes('edit')) idOps.push('put(update)');
  if (crud.includes('delete')) idOps.push('delete(remove)');
  if (idOps.length) {
    lines.push(`.route("/api/${snake}s/:id", ${idOps.join('.')})`);
  }

  return lines.join('\n        ');
}

// ─── Action routes ────────────────────────────────────────────────────────────

function buildActionRoutes(actions: ActionDecl[], _auth: AuthDecl | undefined): string {
  const handlers = actions.map(action => {
    const snake = toSnake(action.name);
    const inputs = action.input?.map(i => `    pub ${toSnake(i.name)}: String,`).join('\n') ?? '';
    return `
#[derive(Debug, serde::Deserialize)]
pub struct ${toPascal(action.name)}Request {
${inputs}
}

async fn ${snake}(
    State(state): State<AppState>,
    auth: crate::middleware::auth::AuthClaims,
    Json(body): Json<${toPascal(action.name)}Request>,
) -> Result<Json<serde_json::Value>, AppError> {
    // ACTION ${action.name} — AI invocation stub
    // Wire to your AI provider using auth.tenant_id for tenant isolation
    Ok(Json(serde_json::json!({ "result": "AI invocation not yet wired" })))
}
`;
  }).join('\n');

  const routes = actions.map(a =>
    `.route("/api/actions/${toSnake(a.name)}", post(${toSnake(a.name)}))`
  ).join('\n        ');

  return `// routes/actions.rs — generated by Agicore
use axum::{extract::State, response::Json, routing::post, Router};
use crate::{db::AppState, error::AppError};
${handlers}
pub fn action_routes() -> Router<AppState> {
    Router::new()
        ${routes}
}
`;
}

// ─── Type mapping helpers ─────────────────────────────────────────────────────

function rustType(field: FieldDef): string {
  const required = field.modifiers.includes('REQUIRED');
  const base = rustBaseType(field.type);
  return required ? base : `Option<${base}>`;
}

function rustTypeInput(field: FieldDef): string {
  const required = field.modifiers.includes('REQUIRED');
  const base = rustBaseType(field.type);
  return required ? base : `Option<${base}>`;
}

function rustBaseType(t: string): string {
  switch (t) {
    case 'string':   return 'String';
    case 'number':   return 'i64';
    case 'float':    return 'f64';
    case 'bool':     return 'bool';
    case 'date':     return 'chrono::NaiveDate';
    case 'datetime': return 'chrono::DateTime<chrono::Utc>';
    case 'json':     return 'serde_json::Value';
    case 'id':       return 'uuid::Uuid';
    default:         return 'String';
  }
}

function toSnake(s: string): string {
  return s
    .replace(/([A-Z])/g, '_$1')
    .toLowerCase()
    .replace(/^_/, '');
}

function toPascal(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase())
    .replace(/^[a-z]/, c => c.toUpperCase());
}
