// Generates cognition role registry, org chart, and per-role documentation
// from COGNITION_ROLE declarations.

import type { AgiFile, CognitionRoleDecl } from '@agicore/parser';

export function generateCognitionRole(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  const roles = ast.cognitionRoles;
  if (!roles || roles.length === 0) return files;

  files.set('src/lib/cognition-roles.ts', generateRegistry(ast.app.name, roles));
  files.set('migrations/cognition_metrics.sql', generateMetricsSql());
  files.set('scaffold/cognition-org-chart.md', generateOrgChart(ast.app.name, roles));

  for (const role of roles) {
    files.set(`scaffold/cognition-roles/${role.name}.md`, generateRoleDoc(role));
  }

  return files;
}

// ─── TypeScript registry ──────────────────────────────────────────────────────

function generateRegistry(appName: string, roles: CognitionRoleDecl[]): string {
  const lines: string[] = [
    `// Cognition Role Registry — generated by Agicore for ${appName}`,
    `// Phase 9: Three-tier cognitive hierarchy with SPC floor governance.`,
    `// Tier 1 = Frontier (ambiguity collapse, novel reasoning)`,
    `// Tier 2 = Operational (implementation, workflow continuation)`,
    `// Tier 3 = Specialized (deterministic tasks, style continuation)`,
    ``,
    `export type PromotionPolicy = 'SPC_AUTOMATIC' | 'MANUAL' | 'DISABLED';`,
    `export type FallbackPolicy  = 'ESCALATE' | 'DEGRADE' | 'FAIL';`,
    `export type CognitionTier   = 1 | 2 | 3;`,
    ``,
    `export interface CognitionSpcFloor {`,
    `  defectRate: number;`,
    `  retryRate: number;`,
    `  escalationRate: number;`,
    `}`,
    ``,
    `export interface CognitionRole {`,
    `  name: string;`,
    `  tier: CognitionTier;`,
    `  responsibilities: string[];`,
    `  qcProfile?: string;`,
    `  escalateTo?: string;`,
    `  modelHierarchy: string[];`,
    `  promotionPolicy: PromotionPolicy;`,
    `  fallbackPolicy: FallbackPolicy;`,
    `  spcFloor?: CognitionSpcFloor;`,
    `}`,
    ``,
    `export const COGNITION_ROLES: Record<string, CognitionRole> = {`,
  ];

  for (const role of roles) {
    lines.push(`  ${role.name}: {`);
    lines.push(`    name: '${role.name}',`);
    lines.push(`    tier: ${role.tier},`);
    lines.push(`    responsibilities: ${JSON.stringify(role.responsibilities)},`);
    if (role.qcProfile) lines.push(`    qcProfile: '${role.qcProfile}',`);
    if (role.escalateTo) lines.push(`    escalateTo: '${role.escalateTo}',`);
    lines.push(`    modelHierarchy: ${JSON.stringify(role.modelHierarchy)},`);
    lines.push(`    promotionPolicy: '${role.promotionPolicy}',`);
    lines.push(`    fallbackPolicy: '${role.fallbackPolicy}',`);
    if (role.spcFloor) {
      lines.push(`    spcFloor: { defectRate: ${role.spcFloor.defectRate}, retryRate: ${role.spcFloor.retryRate}, escalationRate: ${role.spcFloor.escalationRate} },`);
    }
    lines.push(`  },`);
  }

  lines.push(`};`);
  lines.push(``);

  // Tier groupings
  lines.push(`/** Roles grouped by cognitive tier. */`);
  lines.push(`export const COGNITION_TIERS: Record<CognitionTier, CognitionRole[]> = {`);
  for (const t of [1, 2, 3] as const) {
    const tierRoles = roles.filter(r => r.tier === t);
    lines.push(`  ${t}: [${tierRoles.map(r => `COGNITION_ROLES.${r.name}`).join(', ')}],`);
  }
  lines.push(`};`);
  lines.push(``);

  // Resolver functions
  lines.push(`/** Returns the primary model for a cognition role. */`);
  lines.push(`export function resolveRole(roleName: string): CognitionRole | undefined {`);
  lines.push(`  return COGNITION_ROLES[roleName];`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Returns the primary model identifier for a cognition role. */`);
  lines.push(`export function primaryModel(roleName: string): string | undefined {`);
  lines.push(`  return COGNITION_ROLES[roleName]?.modelHierarchy[0];`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Returns the escalation target role name, if defined. */`);
  lines.push(`export function escalationTarget(roleName: string): string | undefined {`);
  lines.push(`  return COGNITION_ROLES[roleName]?.escalateTo;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/** Returns all role names that can handle a given responsibility. */`);
  lines.push(`export function rolesForResponsibility(responsibility: string): string[] {`);
  lines.push(`  return Object.values(COGNITION_ROLES)`);
  lines.push(`    .filter(r => r.responsibilities.includes(responsibility))`);
  lines.push(`    .map(r => r.name);`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Returns the cheapest viable role for a responsibility.`);
  lines.push(` * Prefers the highest tier number (most specialized/cheapest) that`);
  lines.push(` * handles the responsibility. Falls back to lower tiers if needed.`);
  lines.push(` */`);
  lines.push(`export function cheapestViableRole(responsibility: string): CognitionRole | undefined {`);
  lines.push(`  for (const tier of [3, 2, 1] as CognitionTier[]) {`);
  lines.push(`    const match = COGNITION_TIERS[tier].find(r => r.responsibilities.includes(responsibility));`);
  lines.push(`    if (match) return match;`);
  lines.push(`  }`);
  lines.push(`  return undefined;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`/**`);
  lines.push(` * Returns all roles for a given tier, sorted by model hierarchy length`);
  lines.push(` * (more fallback options first).`);
  lines.push(` */`);
  lines.push(`export function resolveByTier(tier: CognitionTier): CognitionRole[] {`);
  lines.push(`  return [...COGNITION_TIERS[tier]].sort((a, b) => b.modelHierarchy.length - a.modelHierarchy.length);`);
  lines.push(`}`);

  return lines.join('\n');
}

// ─── SQL metrics schema ───────────────────────────────────────────────────────

function generateMetricsSql(): string {
  return `-- COGNITION METRICS: per-role SPC quality tracking for tier optimization
-- @agicore-generated — DO NOT EDIT (regenerate via: agicore compile)
CREATE TABLE IF NOT EXISTS cognition_metrics (
  id TEXT PRIMARY KEY,
  role_name TEXT NOT NULL,
  metric_type TEXT NOT NULL,  -- 'defect_rate' | 'retry_rate' | 'escalation_rate'
  value REAL NOT NULL,
  window_size INTEGER NOT NULL DEFAULT 50,
  recorded_at TEXT DEFAULT (datetime('now'))
);
CREATE INDEX IF NOT EXISTS idx_cognition_metrics_role ON cognition_metrics(role_name, metric_type);
CREATE INDEX IF NOT EXISTS idx_cognition_metrics_time ON cognition_metrics(recorded_at);

CREATE VIEW IF NOT EXISTS cognition_tier_allocation AS
SELECT
  role_name,
  metric_type,
  AVG(value) AS avg_value,
  COUNT(*) AS sample_count,
  MAX(recorded_at) AS last_recorded_at
FROM cognition_metrics
GROUP BY role_name, metric_type;
`;
}

// ─── Org chart ───────────────────────────────────────────────────────────────

function generateOrgChart(appName: string, roles: CognitionRoleDecl[]): string {
  const lines: string[] = [
    `# Cognition Org Chart — ${appName}`,
    ``,
    `Auto-generated from Agicore DSL. Shows the escalation hierarchy across all`,
    `defined \`COGNITION_ROLE\` declarations.`,
    ``,
    `## Escalation Hierarchy`,
    ``,
  ];

  // Build adjacency: who escalates to whom
  const escalates = new Map<string, string>(); // child → parent
  for (const role of roles) {
    if (role.escalateTo) escalates.set(role.name, role.escalateTo);
  }

  // Find roots (roles that nobody escalates to, or that nobody references as a child)
  const hasParent = new Set(escalates.keys());
  const roots = roles.filter(r => !hasParent.has(r.name) || !escalates.has(r.name));

  // Simple DFS tree render
  const rendered = new Set<string>();
  function renderRole(name: string, depth: number): void {
    if (rendered.has(name)) return;
    rendered.add(name);
    const role = roles.find(r => r.name === name);
    const indent = '  '.repeat(depth);
    const primary = role?.modelHierarchy[0] ?? '—';
    lines.push(`${indent}- **${name}** _(primary: ${primary})_`);
    // Find children that escalate to this role
    const children = roles.filter(r => r.escalateTo === name);
    for (const child of children) renderRole(child.name, depth + 1);
  }

  for (const root of roots) renderRole(root.name, 0);

  // Any remaining unrendered roles (disconnected)
  for (const role of roles) {
    if (!rendered.has(role.name)) {
      lines.push(`- **${role.name}** _(no escalation chain)_`);
    }
  }

  lines.push(``);
  lines.push(`## Role Summary`);
  lines.push(``);
  lines.push(`| Role | Primary Model | Responsibilities | Escalates To |`);
  lines.push(`|---|---|---|---|`);
  for (const role of roles) {
    const primary = role.modelHierarchy[0] ?? '—';
    const resps = role.responsibilities.join(', ') || '—';
    const esc = role.escalateTo ?? '—';
    lines.push(`| ${role.name} | ${primary} | ${resps} | ${esc} |`);
  }

  return lines.join('\n');
}

// ─── Per-role documentation ───────────────────────────────────────────────────

function generateRoleDoc(role: CognitionRoleDecl): string {
  const lines: string[] = [
    `# Cognition Role: ${role.name}`,
    ``,
    `Auto-generated from Agicore DSL.`,
    ``,
    `## Model Hierarchy`,
    ``,
  ];

  role.modelHierarchy.forEach((m, i) => {
    const label = i === 0 ? ' ← primary' : i === role.modelHierarchy.length - 1 ? ' ← last resort' : '';
    lines.push(`${i + 1}. \`${m}\`${label}`);
  });

  lines.push(``);
  lines.push(`## Responsibilities`);
  lines.push(``);
  for (const r of role.responsibilities) {
    lines.push(`- \`${r}\``);
  }

  if (role.qcProfile) {
    lines.push(``);
    lines.push(`## QC Profile`);
    lines.push(``);
    lines.push(`\`${role.qcProfile}\``);
  }

  if (role.escalateTo) {
    lines.push(``);
    lines.push(`## Escalation`);
    lines.push(``);
    lines.push(`When this role cannot satisfy a request, escalates to: **${role.escalateTo}**`);
  }

  lines.push(``);
  lines.push(`## Policies`);
  lines.push(``);
  lines.push(`| Policy | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Promotion | \`${role.promotionPolicy}\` |`);
  lines.push(`| Fallback  | \`${role.fallbackPolicy}\`  |`);

  lines.push(``);
  lines.push(`## Promotion Policy Notes`);
  lines.push(``);
  if (role.promotionPolicy === 'SPC_AUTOMATIC') {
    lines.push(`**SPC_AUTOMATIC** — The runtime continuously evaluates candidate models from the`);
    lines.push(`hierarchy using NBVE shadow testing. When SPC thresholds remain stable, cheaper`);
    lines.push(`or faster models are automatically promoted without workflow changes.`);
  } else if (role.promotionPolicy === 'MANUAL') {
    lines.push(`**MANUAL** — Model promotion requires explicit operator decision. The system`);
    lines.push(`will surface NBVE candidate recommendations but will not auto-promote.`);
  } else {
    lines.push(`**DISABLED** — Model hierarchy is fixed. No promotion evaluation occurs.`);
  }

  return lines.join('\n');
}
