// Generates Dockerfile, docker-compose.yml, and .env.example for web target.

import type { AgiFile } from '@agicore/parser';

export function generateDocker(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (!ast.target || ast.target.runtime !== 'axum') return files;

  const appName = ast.app.name.toLowerCase().replace(/[^a-z0-9]/g, '-');
  const port = ast.app.port ?? 3000;

  files.set('Dockerfile', buildDockerfile(appName, port));
  files.set('docker-compose.yml', buildDockerCompose(appName, port));
  files.set('.env.example', buildEnvExample(appName, port));
  files.set('.dockerignore', buildDockerIgnore());

  return files;
}

function buildDockerfile(appName: string, port: number): string {
  return `# Dockerfile — generated by Agicore web target
# Multi-stage: Rust backend + Node frontend -> minimal runtime image

# ── Stage 1: Build Rust backend ──────────────────────────────────────────────
FROM rust:1.80-slim-bookworm AS backend-builder
WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release
RUN rm src/main.rs

COPY src ./src
COPY migrations ./migrations
RUN touch src/main.rs && cargo build --release

# ── Stage 2: Build React frontend ────────────────────────────────────────────
FROM node:20-slim AS frontend-builder
WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci

COPY frontend ./
RUN npm run build

# ── Stage 3: Minimal runtime ─────────────────────────────────────────────────
FROM debian:bookworm-slim AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y ca-certificates libssl3 && rm -rf /var/lib/apt/lists/*

COPY --from=backend-builder /app/target/release/${appName} /usr/local/bin/app
COPY --from=backend-builder /app/migrations ./migrations
COPY --from=frontend-builder /app/dist ./frontend/dist

EXPOSE ${port}
ENV PORT=${port}

CMD ["/usr/local/bin/app"]
`;
}

function buildDockerCompose(appName: string, port: number): string {
  return `# docker-compose.yml — generated by Agicore web target
# Development: docker-compose up
# Production: use docker-compose -f docker-compose.prod.yml up

services:
  app:
    build: .
    ports:
      - "${port}:${port}"
    environment:
      DATABASE_URL: postgres://\${POSTGRES_USER:-oie}:\${POSTGRES_PASSWORD:-password}@db:5432/\${POSTGRES_DB:-${appName}db}
      JWT_SECRET: \${JWT_SECRET:-change-me-in-production-use-a-long-random-string}
      PORT: ${port}
      CORS_ORIGIN: \${CORS_ORIGIN:-http://localhost:${port}}
      RUST_LOG: \${RUST_LOG:-info}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-oie}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: \${POSTGRES_DB:-${appName}db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-oie}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
`;
}

function buildEnvExample(appName: string, port: number): string {
  return `# .env.example — generated by Agicore web target
# Copy to .env and fill in values before running

# PostgreSQL connection string
DATABASE_URL=postgres://oie:password@localhost:5432/${appName}db

# JWT signing secret — use a long random string in production
# Generate with: openssl rand -hex 32
JWT_SECRET=change-me-in-production

# Server port
PORT=${port}

# CORS allowed origin (frontend URL)
CORS_ORIGIN=http://localhost:${port}

# Log level: error | warn | info | debug | trace
RUST_LOG=info
`;
}

function buildDockerIgnore(): string {
  return `target/
node_modules/
frontend/node_modules/
.env
.git
*.md
`;
}
