// Generates EscalationChainEngine classes and scaffold docs
// from ESCALATION_CHAIN declarations.

import type { AgiFile, EscalationChainDecl } from '@agicore/parser';

export function generateEscalationChain(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  const chains = ast.escalationChains;
  if (!chains || chains.length === 0) return files;

  files.set('src/lib/escalation-chain.ts', generateChainTs(chains));

  for (const chain of chains) {
    files.set(`scaffold/escalation-chains/${chain.name}.md`, generateChainDoc(chain));
  }

  return files;
}

// ─── TypeScript runtime ───────────────────────────────────────────────────────

function generateChainTs(chains: EscalationChainDecl[]): string {
  const engineBlocks = chains.map(chain => generateEngine(chain)).join('\n\n');

  const registry = [
    `export const ESCALATION_CHAINS: Record<string, EscalationChainEngine> = {`,
    ...chains.map(c => `  ${c.name}: new ${c.name}EscalationChain(),`),
    `};`,
    ``,
    `export function getChain(name: string): EscalationChainEngine | undefined {`,
    `  return ESCALATION_CHAINS[name];`,
    `}`,
  ].join('\n');

  return `// Escalation Chain Engines — generated by Agicore
// @agicore-generated — DO NOT EDIT (regenerate via: agicore compile)

export interface EscalationChainEngine {
  currentRole(): string;
  escalate(): void;
  deescalate(): void;
  shouldEscalate(spcViolations: number, errorRate: number): boolean;
  shouldDeescalate(stableResults: number, errorRate: number): boolean;
  recordViolation(): void;
  recordStableResult(): void;
  isOnCooldown(): boolean;
}

${engineBlocks}

${registry}
`;
}

function generateEngine(chain: EscalationChainDecl): string {
  const roles = JSON.stringify(chain.roles);
  const cooldownMs = parseCooldownMs(chain.cooldown);
  const { escalateOn, deescalateOn } = chain;

  const spcViolationThreshold = escalateOn.spcViolation ?? 3;
  const escalateErrorRate = escalateOn.errorRate ?? 0.15;
  const supportsExplicit = escalateOn.explicit;
  const stabilityWindow = deescalateOn.stabilityWindow ?? 50;
  const deescalateErrorRate = deescalateOn.errorRate ?? 0.05;

  return `// ─── ${chain.name} ─────────────────────────────────────────────────────────────
// ${chain.description}

export class ${chain.name}EscalationChain implements EscalationChainEngine {
  private readonly roles: string[] = ${roles};
  private currentIndex = 0;
  private violationCount = 0;
  private stableCount = 0;
  private lastEscalationAt = 0;
  private readonly cooldownMs = ${cooldownMs};

  currentRole(): string {
    return this.roles[this.currentIndex] ?? this.roles[this.roles.length - 1]!;
  }

  escalate(): void {
    if (this.currentIndex < this.roles.length - 1) {
      this.currentIndex++;
      this.violationCount = 0;
      this.stableCount = 0;
      this.lastEscalationAt = Date.now();
    }
  }

  deescalate(): void {
    if (this.currentIndex > 0) {
      this.currentIndex--;
      this.violationCount = 0;
      this.stableCount = 0;
    }
  }

  shouldEscalate(spcViolations: number, errorRate: number): boolean {
    if (this.isOnCooldown()) return false;
    return spcViolations >= ${spcViolationThreshold} || errorRate >= ${escalateErrorRate};
  }

  shouldDeescalate(stableResults: number, errorRate: number): boolean {
    return stableResults >= ${stabilityWindow} && errorRate <= ${deescalateErrorRate};
  }

  recordViolation(): void {
    this.violationCount++;
    this.stableCount = 0;
    if (this.shouldEscalate(this.violationCount, 0)) {
      this.escalate();
    }
  }

  recordStableResult(): void {
    this.stableCount++;
    this.violationCount = 0;
    if (this.shouldDeescalate(this.stableCount, 0)) {
      this.deescalate();
    }
  }

  isOnCooldown(): boolean {
    return Date.now() - this.lastEscalationAt < this.cooldownMs;
  }

  /** Returns true — ${chain.name} supports explicit escalation calls. */
  get supportsExplicit(): boolean { return ${supportsExplicit}; }
}`;
}

function parseCooldownMs(cooldown: string): number {
  const match = cooldown.match(/^(\d+)(s|m|h)$/);
  if (!match) return 300_000;
  const n = Number(match[1]);
  switch (match[2]) {
    case 's': return n * 1_000;
    case 'm': return n * 60_000;
    case 'h': return n * 3_600_000;
    default:  return 300_000;
  }
}

// ─── Scaffold docs ────────────────────────────────────────────────────────────

function generateChainDoc(chain: EscalationChainDecl): string {
  const { escalateOn, deescalateOn } = chain;
  const lines: string[] = [
    `# Escalation Chain: ${chain.name}`,
    ``,
    `Auto-generated from Agicore DSL.`,
    ``,
    `> ${chain.description}`,
    ``,
    `## Role Hierarchy`,
    ``,
    `Escalation moves **left → right** (cheaper → more capable). De-escalation moves right → left.`,
    ``,
    chain.roles.map((r, i) => `${i + 1}. \`${r}\`${i === 0 ? ' ← entry point' : i === chain.roles.length - 1 ? ' ← ceiling' : ''}`).join('\n'),
    ``,
    `## Escalate On`,
    ``,
    `| Condition | Threshold |`,
    `|---|---|`,
    ...(escalateOn.spcViolation !== undefined ? [`| SPC Violations | ${escalateOn.spcViolation} consecutive |`] : []),
    ...(escalateOn.errorRate !== undefined ? [`| Error Rate | > ${escalateOn.errorRate * 100}% |`] : []),
    `| Explicit Call | ${escalateOn.explicit ? 'Allowed' : 'Not allowed'} |`,
    ``,
    `## De-escalate On`,
    ``,
    `| Condition | Threshold |`,
    `|---|---|`,
    ...(deescalateOn.stabilityWindow !== undefined ? [`| Stable Results | ${deescalateOn.stabilityWindow} consecutive |`] : []),
    ...(deescalateOn.errorRate !== undefined ? [`| Error Rate | < ${deescalateOn.errorRate * 100}% |`] : []),
    ``,
    `## Cooldown`,
    ``,
    `\`${chain.cooldown}\` between escalation events (prevents thrashing).`,
    ``,
    `## Integration`,
    ``,
    `Wire \`CHAIN ${chain.name}\` into any \`NBVE\` block. The \`ShadowRunner\` calls`,
    `\`${chain.name}EscalationChain.recordViolation()\` on FALLBACK and`,
    `\`recordStableResult()\` on promotion-eligible results.`,
    ``,
    `\`\`\`typescript`,
    `import { getChain } from '@/lib/escalation-chain';`,
    `const chain = getChain('${chain.name}');`,
    `chain?.recordViolation();   // on NBVE FALLBACK`,
    `chain?.recordStableResult(); // on stable SPC result`,
    `console.log(chain?.currentRole()); // active role`,
    `\`\`\``,
  ];

  return lines.join('\n');
}
