// Mutation Console UI Generator
//
// Phase 11.8c of the Andon Loop architecture. Surfaces the entire proposal
// lifecycle in a single React component so a human operator can see and
// interact with what the AI is proposing.
//
// Four tabs:
//   Proposals      — every MutationProposal with status, policy, tier,
//                    evidence summary, and verify/sandbox quick-actions.
//   Approvals      — pending approval_requests with signer input field
//                    and approve/reject buttons (multi-signer aware:
//                    shows the signature chain progress).
//   Ledger         — recent hash-chained entries with one-button
//                    integrity verification (runs verify_ledger_integrity).
//   Andon Events   — unresolved andon pulls plus recent resolved ones,
//                    with the linked proposal id when available.
//
// Read-write component — uses every Tauri command we've shipped across
// Phases 4-7. Gated on hasMutationRuntime so apps without policies don't
// ship a useless console.
//
// Style mirrors the existing components.ts pattern: Tailwind utility
// classes, lucide-react icons, useEffect/useState, @agicore-protected
// marker so consumers can customise without regen overwriting their work.

import type { AgiFile } from '@agicore/parser';

function isEnabled(ast: AgiFile): boolean {
  return !!ast.mutationPolicies && ast.mutationPolicies.length > 0;
}

export function generateMutationConsole(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (!isEnabled(ast)) return files;
  files.set('src/components/MutationConsole.tsx', buildConsoleTsx());
  return files;
}

function buildConsoleTsx(): string {
  return `// @agicore-protected — Mutation lifecycle console (Phase 11.8c)
// Generated by Agicore — customize freely; regen won't overwrite this file.
//
// Surfaces every proposal in flight, every pending approval, recent ledger
// entries, and outstanding andon events. Read-write: verify, sandbox,
// approve, reject, integrity-check.

import { useState, useEffect, useCallback } from 'react';
import { Inbox, Shield, BookOpen, AlertOctagon, RefreshCw, CheckCircle2, XCircle, Play, BadgeCheck, Eye, Zap } from 'lucide-react';

import {
  listMutationProposals,
  verifyMutationProposal,
  executeProposalSandbox,
  type MutationProposal,
} from '../lib/mutations';
import {
  listApprovalRequests,
  approveProposal,
  rejectProposal,
  type ApprovalRequest,
} from '../lib/approvals';
import {
  listLedgerEntries,
  verifyLedgerIntegrity,
  type LedgerEntry,
  type IntegrityReport,
} from '../lib/ledger';
import {
  listAndonEvents,
  type AndonEvent,
} from '../lib/workflow';
import {
  listShadowEvaluations,
  finalizeShadowEvaluations,
  evaluateShadowWindow,
  type ShadowEvaluation,
} from '../lib/shadow_eval';

type Tab = 'proposals' | 'approvals' | 'shadow' | 'ledger' | 'andon';

const TABS: { id: Tab; label: string; icon: typeof Inbox }[] = [
  { id: 'proposals', label: 'Proposals',     icon: Inbox },
  { id: 'approvals', label: 'Approvals',     icon: Shield },
  { id: 'shadow',    label: 'Shadow',        icon: Eye },
  { id: 'ledger',    label: 'Ledger',        icon: BookOpen },
  { id: 'andon',     label: 'Andon Events',  icon: AlertOctagon },
];

const STATUS_COLOR: Record<string, string> = {
  created:           'bg-gray-700  text-gray-200',
  tier_verified:     'bg-blue-700  text-blue-100',
  tier_rejected:     'bg-red-800   text-red-100',
  tested:            'bg-blue-800  text-blue-100',
  shadow_evaluating: 'bg-purple-700 text-purple-100',  // Phase 11.5e
  collecting:        'bg-purple-700 text-purple-100',
  sufficient_data:   'bg-purple-800 text-purple-100',
  promoted:          'bg-emerald-700 text-emerald-100',
  inconclusive:      'bg-amber-700 text-amber-100',
  deployed:          'bg-emerald-700 text-emerald-100',
  rejected:          'bg-red-700   text-red-100',
  escalated:         'bg-amber-700 text-amber-100',
  rolled_back:       'bg-orange-700 text-orange-100',
  pending:           'bg-amber-700 text-amber-100',
  approved:          'bg-emerald-700 text-emerald-100',
};

function StatusPill({ status }: { status: string }) {
  const cls = STATUS_COLOR[status] ?? 'bg-gray-700 text-gray-200';
  return <span className={\`text-xs px-2 py-0.5 rounded font-mono \${cls}\`}>{status}</span>;
}

function ShortId({ id }: { id: string }) {
  return <span className="text-xs text-gray-500 font-mono">{id.substring(0, 8)}</span>;
}

export function MutationConsole() {
  const [tab, setTab] = useState<Tab>('proposals');

  return (
    <div className="flex flex-col h-full bg-gray-900 text-gray-100">
      <div className="flex items-center gap-3 px-6 py-4 border-b border-gray-800">
        <BadgeCheck size={20} className="text-emerald-400" />
        <h1 className="text-lg font-semibold">Mutation Console</h1>
        <span className="text-xs text-gray-500 ml-2">Andon Loop · Proposal lifecycle</span>
      </div>
      <div className="flex border-b border-gray-800">
        {TABS.map((t) => {
          const Icon = t.icon;
          const active = tab === t.id;
          return (
            <button
              key={t.id}
              onClick={() => setTab(t.id)}
              className={\`flex items-center gap-2 px-5 py-3 text-sm border-b-2 \${
                active
                  ? 'border-emerald-400 text-emerald-300'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }\`}
            >
              <Icon size={15} />
              {t.label}
            </button>
          );
        })}
      </div>
      <div className="flex-1 overflow-auto">
        {tab === 'proposals' && <ProposalsPane />}
        {tab === 'approvals' && <ApprovalsPane />}
        {tab === 'shadow'    && <ShadowPane />}
        {tab === 'ledger'    && <LedgerPane />}
        {tab === 'andon'     && <AndonPane />}
      </div>
    </div>
  );
}

// ─── Proposals tab ─────────────────────────────────────────────────────────

function ProposalsPane() {
  const [items, setItems] = useState<MutationProposal[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try { setItems(await listMutationProposals({ limit: 100 })); }
    catch (e) { console.error(e); }
    setLoading(false);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  async function verify(id: string) {
    setBusy(id);
    try { await verifyMutationProposal(id); await refresh(); }
    catch (e) { console.error(e); }
    setBusy(null);
  }
  async function sandbox(id: string) {
    setBusy(id);
    try { await executeProposalSandbox(id); await refresh(); }
    catch (e) { console.error(e); }
    setBusy(null);
  }

  return (
    <div className="p-6">
      <div className="flex items-center mb-4">
        <span className="text-sm text-gray-400">{items.length} proposal(s)</span>
        <button onClick={refresh} className="ml-auto p-1.5 hover:bg-gray-800 rounded" title="Refresh">
          <RefreshCw size={15} />
        </button>
      </div>
      {loading ? <div className="text-gray-500">Loading…</div> : (
        <div className="space-y-2">
          {items.map((p) => (
            <div key={p.id} className="border border-gray-800 rounded-lg p-4 hover:border-gray-700">
              <div className="flex items-center gap-2 mb-2">
                <ShortId id={p.id} />
                <StatusPill status={p.status} />
                <span className="text-xs text-gray-500">
                  T{p.claimedTier}{p.resolvedTier !== null && p.resolvedTier !== p.claimedTier ? \` → T\${p.resolvedTier}\` : ''}
                </span>
                <span className="text-xs text-gray-500 font-mono">{p.policyName}</span>
                <span className="text-xs text-gray-400 ml-auto">{p.proposerIdentity}</span>
              </div>
              <div className="text-sm text-gray-300 mb-1">
                Target: <span className="font-mono">{p.target}</span>
              </div>
              <div className="text-xs text-gray-500 mb-2">
                Scope: {p.claimedScope.join(', ')} · Created {new Date(p.createdAt).toLocaleString()}
              </div>
              {p.rejectionReason && (
                <div className="text-xs text-red-300 mb-2">⚠ {p.rejectionReason}</div>
              )}
              <div className="flex gap-2">
                {p.status === 'created' && (
                  <button
                    onClick={() => verify(p.id)}
                    disabled={busy === p.id}
                    className="text-xs px-3 py-1 bg-blue-700 hover:bg-blue-600 rounded disabled:opacity-50"
                  >
                    <CheckCircle2 size={12} className="inline mr-1" />Verify Tier
                  </button>
                )}
                {p.status === 'tier_verified' && (
                  <button
                    onClick={() => sandbox(p.id)}
                    disabled={busy === p.id}
                    className="text-xs px-3 py-1 bg-blue-700 hover:bg-blue-600 rounded disabled:opacity-50"
                  >
                    <Play size={12} className="inline mr-1" />Run Sandbox
                  </button>
                )}
              </div>
            </div>
          ))}
          {items.length === 0 && (
            <div className="text-gray-500 text-sm py-8 text-center">No proposals yet.</div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Approvals tab ─────────────────────────────────────────────────────────

function ApprovalsPane() {
  const [items, setItems] = useState<ApprovalRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [signer, setSigner] = useState('');
  const [busy, setBusy] = useState<string | null>(null);
  const [notes, setNotes] = useState<Record<string, string>>({});

  const refresh = useCallback(async () => {
    setLoading(true);
    try { setItems(await listApprovalRequests({ status: 'pending', limit: 50 })); }
    catch (e) { console.error(e); }
    setLoading(false);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  async function approve(id: string) {
    if (!signer.trim()) { alert('Enter signer identity'); return; }
    setBusy(id);
    try { await approveProposal(id, signer.trim(), notes[id]); await refresh(); }
    catch (e) { alert(String(e)); }
    setBusy(null);
  }
  async function reject(id: string) {
    if (!signer.trim()) { alert('Enter signer identity'); return; }
    setBusy(id);
    try { await rejectProposal(id, signer.trim(), notes[id]); await refresh(); }
    catch (e) { alert(String(e)); }
    setBusy(null);
  }

  return (
    <div className="p-6">
      <div className="flex items-center gap-2 mb-4">
        <span className="text-sm text-gray-400">Signing as:</span>
        <input
          value={signer}
          onChange={(e) => setSigner(e.target.value)}
          placeholder="signer-identity"
          className="px-2 py-1 text-sm bg-gray-800 border border-gray-700 rounded font-mono w-64"
        />
        <button onClick={refresh} className="ml-auto p-1.5 hover:bg-gray-800 rounded">
          <RefreshCw size={15} />
        </button>
      </div>
      {loading ? <div className="text-gray-500">Loading…</div> : (
        <div className="space-y-2">
          {items.map((r) => (
            <div key={r.id} className="border border-gray-800 rounded-lg p-4 hover:border-gray-700">
              <div className="flex items-center gap-2 mb-2">
                <ShortId id={r.proposalId} />
                <StatusPill status={r.status} />
                <span className="text-xs text-gray-500 font-mono">{r.policyName}</span>
                <span className="text-xs text-gray-400 ml-auto">{new Date(r.requestedAt).toLocaleString()}</span>
              </div>
              {r.requiredAuthority && (
                <div className="text-xs text-gray-500 mb-2">
                  Required: <span className="font-mono">{r.requiredAuthority}</span>
                </div>
              )}
              <input
                value={notes[r.id] ?? ''}
                onChange={(e) => setNotes({ ...notes, [r.id]: e.target.value })}
                placeholder="Decision notes (optional)"
                className="w-full px-2 py-1 text-xs bg-gray-800 border border-gray-700 rounded mb-2"
              />
              <div className="flex gap-2">
                <button
                  onClick={() => approve(r.proposalId)}
                  disabled={busy === r.id}
                  className="text-xs px-3 py-1 bg-emerald-700 hover:bg-emerald-600 rounded disabled:opacity-50"
                >
                  <CheckCircle2 size={12} className="inline mr-1" />Approve
                </button>
                <button
                  onClick={() => reject(r.proposalId)}
                  disabled={busy === r.id}
                  className="text-xs px-3 py-1 bg-red-700 hover:bg-red-600 rounded disabled:opacity-50"
                >
                  <XCircle size={12} className="inline mr-1" />Reject
                </button>
              </div>
            </div>
          ))}
          {items.length === 0 && (
            <div className="text-gray-500 text-sm py-8 text-center">No pending approvals.</div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Ledger tab ────────────────────────────────────────────────────────────

function LedgerPane() {
  const [items, setItems] = useState<LedgerEntry[]>([]);
  const [integrity, setIntegrity] = useState<IntegrityReport | null>(null);
  const [loading, setLoading] = useState(true);
  const [checking, setChecking] = useState(false);

  const refresh = useCallback(async () => {
    setLoading(true);
    try { setItems(await listLedgerEntries({ limit: 50 })); }
    catch (e) { console.error(e); }
    setLoading(false);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  async function checkIntegrity() {
    setChecking(true);
    try { setIntegrity(await verifyLedgerIntegrity()); }
    catch (e) { console.error(e); }
    setChecking(false);
  }

  return (
    <div className="p-6">
      <div className="flex items-center gap-2 mb-4">
        <button
          onClick={checkIntegrity}
          disabled={checking}
          className="text-xs px-3 py-1 bg-emerald-700 hover:bg-emerald-600 rounded disabled:opacity-50"
        >
          {checking ? 'Checking…' : 'Verify Integrity'}
        </button>
        {integrity && (
          <span className={\`text-xs px-2 py-1 rounded \${
            integrity.allGood ? 'bg-emerald-900 text-emerald-200' : 'bg-red-900 text-red-200'
          }\`}>
            {integrity.allGood
              ? \`✓ \${integrity.chainsVerified}/\${integrity.totalEntries} entries OK\`
              : \`✗ Broken at seq \${integrity.brokenChainAtSequence}: \${integrity.brokenChainReason}\`}
          </span>
        )}
        <button onClick={refresh} className="ml-auto p-1.5 hover:bg-gray-800 rounded">
          <RefreshCw size={15} />
        </button>
      </div>
      {loading ? <div className="text-gray-500">Loading…</div> : (
        <div className="space-y-1">
          {items.map((e) => (
            <div key={e.id} className="text-xs font-mono py-1.5 px-3 border-l-2 border-gray-700 hover:border-emerald-500 hover:bg-gray-800/50">
              <div className="flex items-center gap-3">
                <span className="text-gray-500 w-12">#{e.sequenceNum}</span>
                <span className="text-emerald-400 w-44">{e.eventType}</span>
                <ShortId id={e.proposalId} />
                <span className="text-gray-400">{e.actor}</span>
                <span className="text-gray-500 ml-auto">{new Date(e.recordedAt).toLocaleString()}</span>
              </div>
              <div className="text-gray-600 ml-15 mt-0.5 text-[10px] truncate">
                hash: {e.selfHash.substring(0, 16)}… · prev: {e.prevHash.substring(0, 16)}…
              </div>
            </div>
          ))}
          {items.length === 0 && (
            <div className="text-gray-500 text-sm py-8 text-center">Ledger is empty.</div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Shadow tab (Phase 11.5e) ─────────────────────────────────────────────

function ShadowPane() {
  const [items, setItems] = useState<ShadowEvaluation[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState<string | null>(null);
  const [finalizing, setFinalizing] = useState(false);
  const [lastOutcome, setLastOutcome] = useState<string | null>(null);

  const refresh = useCallback(async () => {
    setLoading(true);
    try { setItems(await listShadowEvaluations({ limit: 50 })); }
    catch (e) { console.error(e); }
    setLoading(false);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  async function evalNow(proposalId: string) {
    setBusy(proposalId);
    try { await evaluateShadowWindow(proposalId); await refresh(); }
    catch (e) { console.error(e); }
    setBusy(null);
  }

  async function finalizeAll() {
    setFinalizing(true);
    try {
      const r = await finalizeShadowEvaluations();
      setLastOutcome(\`Reviewed \${r.totalActive}: \${r.promoted} promoted, \${r.rolledBack} rolled back, \${r.inconclusive} inconclusive, \${r.stillCollecting} still collecting\`);
      await refresh();
    } catch (e) { console.error(e); }
    setFinalizing(false);
  }

  return (
    <div className="p-6">
      <div className="flex items-center gap-2 mb-4">
        <button
          onClick={finalizeAll}
          disabled={finalizing}
          className="text-xs px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded disabled:opacity-50"
        >
          <Zap size={12} className="inline mr-1" />
          {finalizing ? 'Finalizing…' : 'Finalize All Windows'}
        </button>
        {lastOutcome && <span className="text-xs text-gray-400">{lastOutcome}</span>}
        <button onClick={refresh} className="ml-auto p-1.5 hover:bg-gray-800 rounded">
          <RefreshCw size={15} />
        </button>
      </div>
      {loading ? <div className="text-gray-500">Loading…</div> : (
        <div className="space-y-2">
          {items.map((s) => (
            <div key={s.id} className="border border-gray-800 rounded-lg p-4 hover:border-gray-700">
              <div className="flex items-center gap-2 mb-2">
                <Eye size={14} className="text-purple-400" />
                <ShortId id={s.proposalId} />
                <StatusPill status={s.status} />
                <span className="text-xs text-gray-500">
                  {s.samplesCount} samples ({s.samplesDiverged} diverged)
                </span>
                {s.defectRate !== null && (
                  <span className={\`text-xs font-mono \${
                    s.defectRate <= s.defectThreshold ? 'text-emerald-400' : 'text-red-400'
                  }\`}>
                    defect_rate={s.defectRate.toFixed(4)} ≤ {s.defectThreshold.toFixed(4)}
                  </span>
                )}
                <span className="text-xs text-gray-400 ml-auto">
                  window {new Date(s.windowEndsAt).toLocaleString()}
                </span>
              </div>
              {s.notes && <div className="text-xs text-gray-400 mb-2">{s.notes}</div>}
              {s.status === 'collecting' && (
                <button
                  onClick={() => evalNow(s.proposalId)}
                  disabled={busy === s.proposalId}
                  className="text-xs px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded disabled:opacity-50"
                >
                  Evaluate Now
                </button>
              )}
            </div>
          ))}
          {items.length === 0 && (
            <div className="text-gray-500 text-sm py-8 text-center">No shadow evaluations.</div>
          )}
        </div>
      )}
    </div>
  );
}

// ─── Andon Events tab ─────────────────────────────────────────────────────

function AndonPane() {
  const [items, setItems] = useState<AndonEvent[]>([]);
  const [loading, setLoading] = useState(true);

  const refresh = useCallback(async () => {
    setLoading(true);
    try { setItems(await listAndonEvents(undefined, undefined, 50)); }
    catch (e) { console.error(e); }
    setLoading(false);
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  return (
    <div className="p-6">
      <div className="flex items-center mb-4">
        <span className="text-sm text-gray-400">{items.length} event(s)</span>
        <button onClick={refresh} className="ml-auto p-1.5 hover:bg-gray-800 rounded">
          <RefreshCw size={15} />
        </button>
      </div>
      {loading ? <div className="text-gray-500">Loading…</div> : (
        <div className="space-y-2">
          {items.map((e) => (
            <div
              key={e.id}
              className={\`border rounded-lg p-4 \${
                e.resolvedAt ? 'border-gray-800 opacity-70' : 'border-amber-700 bg-amber-700/5'
              }\`}
            >
              <div className="flex items-center gap-2 mb-2">
                <AlertOctagon size={14} className={e.resolvedAt ? 'text-gray-500' : 'text-amber-400'} />
                <ShortId id={e.id} />
                <span className="text-xs font-mono px-2 py-0.5 rounded bg-amber-900 text-amber-200">
                  {e.triggerCategory}
                </span>
                <span className="text-xs text-gray-400">{e.workflowName ?? '(no workflow)'}</span>
                {e.resolvedAt && (
                  <span className="text-xs text-emerald-400 ml-auto">resolved</span>
                )}
              </div>
              {e.failureMessage && (
                <div className="text-sm text-gray-300 mb-1">{e.failureMessage}</div>
              )}
              <div className="text-xs text-gray-500">
                fired {new Date(e.firedAt).toLocaleString()}
                {e.resolutionMutationId && (
                  <> · proposal <ShortId id={e.resolutionMutationId} /></>
                )}
              </div>
            </div>
          ))}
          {items.length === 0 && (
            <div className="text-gray-500 text-sm py-8 text-center">No andon events.</div>
          )}
        </div>
      )}
    </div>
  );
}
`;
}
