// Generates QC_MESH consensus evaluator classes and scaffold docs.

import type { AgiFile, QcMeshDecl, QcMeshConsensus } from '@agicore/parser';

export function generateQcMesh(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  const meshes = ast.qcMeshes;
  if (!meshes || meshes.length === 0) return files;

  files.set('src/lib/qc-mesh.ts', buildMeshTs(meshes));

  for (const mesh of meshes) {
    files.set(`scaffold/qc-meshes/${mesh.name}.md`, buildMeshDoc(mesh));
  }

  return files;
}

function consensusThreshold(c: QcMeshConsensus): string {
  if (c === 'majority') return '0.5';
  if (c === 'all') return '1.0';
  return String(c);
}

function buildMeshTs(meshes: QcMeshDecl[]): string {
  const classes = meshes.map(m => buildEngineClass(m)).join('\n\n');

  const registry = [
    `export const QC_MESHES: Record<string, QcMeshEngine> = {`,
    ...meshes.map(m => `  ${m.name}: new ${m.name}QcMesh(),`),
    `};`,
    ``,
    `export function getMesh(name: string): QcMeshEngine | undefined {`,
    `  return QC_MESHES[name];`,
    `}`,
  ].join('\n');

  return `// QC Mesh Engines — generated by Agicore
// @agicore-generated — DO NOT EDIT (regenerate via: agicore compile)
//
// Architecture: N independent evaluator models each assess output quality.
// If each catches judgment drift at rate p, N independent evaluators give
// combined miss rate of (1-p)^N — approaching six sigma with diverse models.
// SPC governs active evaluator count dynamically.

export interface EvaluatorResult {
  model: string;
  verdict: 'pass' | 'fail';
  confidence: number;
  reasoning?: string;
}

export interface MeshVerdict {
  passed: boolean;
  consensus: number;        // 0.0–1.0 fraction of evaluators that passed
  activeEvaluators: number;
  results: EvaluatorResult[];
  driftDetected: boolean;
}

export interface QcMeshEngine {
  evaluate(output: string, criteriaPrompt: string): Promise<MeshVerdict>;
  activeCount(): number;
  driftRate(): number;
}

${classes}

${registry}
`;
}

function buildEngineClass(mesh: QcMeshDecl): string {
  const evaluatorsList = JSON.stringify(mesh.evaluators);
  const threshold = consensusThreshold(mesh.consensus);
  const onFail = mesh.onFail;

  return `// ─── ${mesh.name} ─────────────────────────────────────────────────────────────
// ${mesh.description}
// Criteria: ${mesh.criteria} | Consensus: ${mesh.consensus} | On fail: ${onFail}

export class ${mesh.name}QcMesh implements QcMeshEngine {
  private readonly allEvaluators: string[] = ${evaluatorsList};
  private _activeCount = ${mesh.spc.minEvaluators};
  private stableResults = 0;
  private driftCount = 0;
  private totalRuns = 0;
  private readonly spc = {
    minEvaluators: ${mesh.spc.minEvaluators},
    maxEvaluators: ${mesh.spc.maxEvaluators},
    driftRate: ${mesh.spc.driftRate},
    stabilityWindow: ${mesh.spc.stabilityWindow},
  };

  activeCount(): number { return this._activeCount; }

  driftRate(): number {
    return this.totalRuns === 0 ? 0 : this.driftCount / this.totalRuns;
  }

  async evaluate(
    output: string,
    criteriaPrompt: string,
    invokeAi: (model: string, prompt: string) => Promise<string>
  ): Promise<MeshVerdict> {
    const evaluators = this.selectEvaluators();
    const prompt = this.buildEvaluatorPrompt(output, criteriaPrompt);

    const results: EvaluatorResult[] = await Promise.all(
      evaluators.map(model => this.runEvaluator(model, prompt, invokeAi))
    );

    const passCount = results.filter(r => r.verdict === 'pass').length;
    const consensus = passCount / results.length;
    const passed = consensus > ${threshold};
    const driftDetected = !passed;

    this.totalRuns++;
    if (driftDetected) {
      this.driftCount++;
      this.stableResults = 0;
    } else {
      this.stableResults++;
    }

    this.adjustMeshSize();

    return { passed, consensus, activeEvaluators: evaluators.length, results, driftDetected };
  }

  private selectEvaluators(): string[] {
    // Shuffle for diversity across runs, then take activeCount
    const pool = [...this.allEvaluators];
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j]!, pool[i]!];
    }
    return pool.slice(0, Math.min(this._activeCount, pool.length));
  }

  private async runEvaluator(
    model: string,
    prompt: string,
    invokeAi: (model: string, prompt: string) => Promise<string>
  ): Promise<EvaluatorResult> {
    try {
      const response = await invokeAi(model, prompt);
      const verdict = response.toLowerCase().includes('pass') ? 'pass' : 'fail';
      return { model, verdict, confidence: 0.92, reasoning: response.slice(0, 200) };
    } catch {
      return { model, verdict: 'fail', confidence: 0, reasoning: 'evaluator error' };
    }
  }

  private buildEvaluatorPrompt(output: string, criteriaPrompt: string): string {
    return \`You are a quality evaluator. Assess whether the following output meets the criteria below.
Reply with PASS if it meets the criteria, or FAIL with brief reasoning if it does not.

CRITERIA:
\${criteriaPrompt}

OUTPUT TO EVALUATE:
\${output}

Verdict (PASS or FAIL):\`;
  }

  private adjustMeshSize(): void {
    const currentDriftRate = this.driftRate();
    if (currentDriftRate > this.spc.driftRate && this._activeCount < this.spc.maxEvaluators) {
      // Drift detected — expand mesh
      this._activeCount = Math.min(this._activeCount + 1, this.spc.maxEvaluators);
      this.stableResults = 0;
    } else if (this.stableResults >= this.spc.stabilityWindow && this._activeCount > this.spc.minEvaluators) {
      // Stable — contract mesh
      this._activeCount = Math.max(this._activeCount - 1, this.spc.minEvaluators);
      this.stableResults = 0;
    }
  }
}`;
}

function buildMeshDoc(mesh: QcMeshDecl): string {
  const threshold = consensusThreshold(mesh.consensus);
  const thresholdPct = Math.round(Number(threshold) * 100);
  const n = mesh.spc.maxEvaluators;
  const singleMissRate = 0.08; // assumes 92% detection rate
  const combinedMissRate = Math.pow(singleMissRate, n);
  const sigma = combinedMissRate < 0.0000034 ? '≥ 6σ' : combinedMissRate < 0.000233 ? '≥ 5σ' : '≥ 4σ';

  const lines: string[] = [
    `# QC Mesh: ${mesh.name}`,
    ``,
    `Auto-generated from Agicore DSL.`,
    ``,
    `> ${mesh.description}`,
    ``,
    `## Evaluator Pool`,
    ``,
    `| # | Model | Role |`,
    `|---|---|---|`,
    ...mesh.evaluators.map((e, i) => `| ${i + 1} | \`${e}\` | Independent evaluator |`),
    ``,
    `**Active at runtime:** ${mesh.spc.minEvaluators}–${mesh.spc.maxEvaluators} (SPC-governed)`,
    ``,
    `## Statistical Quality`,
    ``,
    `At ${thresholdPct}% consensus threshold, assuming 92% per-evaluator detection rate:`,
    ``,
    `| Active Evaluators | Combined Miss Rate | Quality Level |`,
    `|---|---|---|`,
    ...Array.from({ length: mesh.spc.maxEvaluators - mesh.spc.minEvaluators + 1 }, (_, k) => {
      const count = mesh.spc.minEvaluators + k;
      const miss = Math.pow(singleMissRate, count);
      const perMillion = (miss * 1_000_000).toFixed(2);
      const level = miss < 0.0000034 ? '≥ 6σ' : miss < 0.000233 ? '≥ 5σ' : miss < 0.00621 ? '≥ 4σ' : '≥ 3σ';
      return `| ${count} | ${perMillion}/million | ${level} |`;
    }),
    ``,
    `At maximum mesh size (${n} evaluators), combined miss rate ≈ ${(Math.pow(singleMissRate, n) * 1e6).toFixed(2)} per million — ${sigma}.`,
    ``,
    `**Assumes evaluator independence.** Use diverse model families to preserve the statistical guarantee.`,
    ``,
    `## Consensus Rule`,
    ``,
    `**${typeof mesh.consensus === 'number' ? `Threshold: ${mesh.consensus * 100}%` : mesh.consensus.charAt(0).toUpperCase() + mesh.consensus.slice(1)}** — requires ${thresholdPct}%+ of active evaluators to agree.`,
    ``,
    `## On Fail: \`${mesh.onFail}\``,
    ``,
    ...(mesh.onFail === 'escalate' ? [
      `When consensus fails, the result is escalated to the bound \`ESCALATION_CHAIN\` or`,
      `the next \`COGNITION_ROLE\` in the hierarchy.`,
    ] : mesh.onFail === 'reject' ? [
      `When consensus fails, the output is rejected and the action is retried or aborted.`,
    ] : [
      `When consensus fails, the output is flagged for human review but allowed through.`,
    ]),
    ``,
    `## SPC Mesh Sizing`,
    ``,
    `| Parameter | Value |`,
    `|---|---|`,
    `| Min evaluators | ${mesh.spc.minEvaluators} |`,
    `| Max evaluators | ${mesh.spc.maxEvaluators} |`,
    `| Expand when drift rate > | ${mesh.spc.driftRate * 100}% |`,
    `| Shrink after stable window of | ${mesh.spc.stabilityWindow} results |`,
    ``,
    `## Criteria Reference`,
    ``,
    `This mesh evaluates against: **\`${mesh.criteria}\`**`,
    ``,
    `The criteria SKILLDOC defines what "good judgment" looks like for this domain.`,
    `Non-engineers own this document — it is prose, not code.`,
    ``,
    `## Integration`,
    ``,
    `Bind this mesh to a \`COGNITION_ROLE\` via \`QC_PROFILE\`:`,
    ``,
    `\`\`\`agi`,
    `COGNITION_ROLE ContentWriter {`,
    `  QC_PROFILE   ${mesh.name}`,
    `  ...`,
    `}`,
    `\`\`\``,
    ``,
    `Or use at ACTION level with a \`QC\` reference (future primitive).`,
    ``,
    `\`\`\`typescript`,
    `import { getMesh } from '@/lib/qc-mesh';`,
    `const mesh = getMesh('${mesh.name}');`,
    `const verdict = await mesh?.evaluate(output, criteriaPrompt, invokeAi);`,
    `if (verdict && !verdict.passed) { /* handle ${mesh.onFail} */ }`,
    `\`\`\``,
  ];

  return lines.join('\n');
}
