import type { AgiFile, ReasonerDecl } from '@agicore/parser';

// ─── Main entry point ─────────────────────────────────────────────────────────

export function generateReasoner(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (ast.reasoners.length === 0) return files;

  const rs = generateReasonerRs(ast);
  if (rs) files.set('src-tauri/src/commands/reasoner.rs', rs);

  files.set('migrations/reasoner_runs.sql', generateReasonerMigration());

  const tsx = generateReasonerViewTsx(ast);
  if (tsx) files.set('src/components/ReasonerView.tsx', tsx);

  return files;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toSnake(s: string): string {
  return s.replace(/[^a-zA-Z0-9]+/g, '_').replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}

function scheduleToThresholdHours(schedule: string): number | null {
  switch (schedule) {
    case 'hourly':  return 1;
    case 'daily':   return 22;
    case 'weekly':  return 160;
    default:        return null; // on_demand / event_triggered / cron — no auto-run
  }
}

// ─── SQL migration fragment ───────────────────────────────────────────────────

export function generateReasonerMigration(): string {
  return `
-- REASONER: persistent run history
CREATE TABLE IF NOT EXISTS reasoner_runs (
  id TEXT PRIMARY KEY,
  reasoner_name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  records_analyzed INTEGER NOT NULL DEFAULT 0,
  output TEXT,
  error TEXT,
  model TEXT,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_reasoner_runs_name ON reasoner_runs(reasoner_name);
CREATE INDEX IF NOT EXISTS idx_reasoner_runs_started ON reasoner_runs(started_at DESC);
`.trim();
}

// ─── Rust reasoner.rs emitter ─────────────────────────────────────────────────

export function generateReasonerRs(ast: AgiFile): string {
  if (ast.reasoners.length === 0) return '';

  const defs = ast.reasoners.map((r) => {
    const windowDays = parseWindowToDays(r.input.window ?? '7d');
    const inputQuery = buildInputQuery(r, ast);
    const systemPrompt = r.uses
      ? `// Uses SKILLDOC: ${r.uses} — replace this stub with the actual prompt`
      : 'Analyze the provided data and surface key insights, patterns, and actionable recommendations.';

    return `    ReasonerDef {
        name: "${r.name}",
        description: "${r.description.replace(/"/g, '\\"')}",
        schedule: "${r.schedule}",
        system_prompt: "${(typeof r.uses === 'string' ? systemPrompt : r.uses ?? systemPrompt).replace(/"/g, '\\"')}",
        window_days: ${windowDays},
        input_query: "${inputQuery.replace(/"/g, '\\"')}",
    },`;
  }).join('\n');

  const schedulerEntries = ast.reasoners.map((r) => {
    const hours = scheduleToThresholdHours(r.schedule);
    if (!hours) return '';
    return `
            if should_auto_run(&db, "${r.name}", ${hours}) {
                run_scheduled_reasoner(&app, &db, &keys_snap, "${r.name}", &default_model).await;
            }`;
  }).filter(Boolean).join('\n');

  const hasScheduled = ast.reasoners.some((r) => scheduleToThresholdHours(r.schedule) !== null);

  return `// REASONER runtime — generated by Agicore
// Periodic AI analysis loops: read from channels, call AI, store + emit insights.

use serde::{Deserialize, Serialize};
use tauri::{AppHandle, Emitter, State};
use crate::ai_service::{chat_complete, ApiKeyStore};
use crate::db::DbPool;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasonerRun {
    pub id: String,
    pub reasoner_name: String,
    pub status: String,
    pub records_analyzed: i64,
    pub output: Option<String>,
    pub error: Option<String>,
    pub model: Option<String>,
    pub started_at: String,
    pub completed_at: Option<String>,
    pub created_at: String,
}

impl ReasonerRun {
    fn from_row(row: &rusqlite::Row) -> Self {
        Self {
            id: row.get("id").unwrap(),
            reasoner_name: row.get("reasoner_name").unwrap(),
            status: row.get("status").unwrap(),
            records_analyzed: row.get("records_analyzed").unwrap_or(0),
            output: row.get("output").ok(),
            error: row.get("error").ok(),
            model: row.get("model").ok(),
            started_at: row.get("started_at").unwrap(),
            completed_at: row.get("completed_at").ok(),
            created_at: row.get("created_at").unwrap(),
        }
    }
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ReasonerStatus {
    pub name: String,
    pub description: String,
    pub schedule: String,
    pub last_run: Option<ReasonerRun>,
}

struct ReasonerDef {
    name: &'static str,
    description: &'static str,
    schedule: &'static str,
    system_prompt: &'static str,
    window_days: i64,
    input_query: &'static str,
}

const REASONERS: &[ReasonerDef] = &[
${defs}
];

async fn execute_reasoner(
    name: &str,
    model: &str,
    db: &DbPool,
    keys: &std::collections::HashMap<String, String>,
) -> Result<(i64, String), String> {
    let def = REASONERS.iter().find(|r| r.name == name)
        .ok_or_else(|| format!("Unknown reasoner: {}", name))?;

    let query = def.input_query.replace("{window}", &def.window_days.to_string());

    let (record_count, user_content) = {
        let conn = db.lock().map_err(|e| e.to_string())?;
        let mut stmt = conn.prepare(&query).map_err(|e| e.to_string())?;
        let mut rows_text = String::new();
        let mut count = 0i64;

        let rows = stmt.query_map([], |row| {
            Ok((
                row.get::<_, String>(0).unwrap_or_default(),
                row.get::<_, String>(1).unwrap_or_default(),
                row.get::<_, String>(2).unwrap_or_default(),
            ))
        }).map_err(|e| e.to_string())?;

        for row in rows {
            let (col0, col1, col2) = row.map_err(|e| e.to_string())?;
            count += 1;
            let c1 = if col1.len() > 500 { format!("{}…", &col1[..500]) } else { col1 };
            let c2 = if col2.len() > 800 { format!("{}…", &col2[..800]) } else { col2 };
            rows_text.push_str(&format!("[{}] {}\\n{}\\n\\n", col2, c0, c1));
            let _ = c0; // suppress warning
            let _ = c2;
        }

        if count == 0 {
            return Ok((0, "No data found in the analysis window.".to_string()));
        }

        let capped = if rows_text.len() > 12_000 {
            format!("{}…\\n[Truncated — {} total records]", &rows_text[..12_000], count)
        } else {
            rows_text
        };
        (count, capped)
    };

    let output = chat_complete(def.system_prompt, &user_content, model, keys).await?;
    Ok((record_count, output))
}

fn db_start_run(db: &DbPool, name: &str, model: &str) -> Result<String, String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    let id = uuid::Uuid::new_v4().to_string();
    let now = chrono::Utc::now().to_rfc3339();
    conn.execute(
        "INSERT INTO reasoner_runs (id, reasoner_name, status, records_analyzed, model, started_at, created_at, updated_at) VALUES (?, ?, 'running', 0, ?, ?, ?, ?)",
        rusqlite::params![id, name, model, now, now, now],
    ).map_err(|e| e.to_string())?;
    Ok(id)
}

fn db_finish_run(db: &DbPool, id: &str, records: i64, output: &str) -> Result<(), String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    let now = chrono::Utc::now().to_rfc3339();
    conn.execute(
        "UPDATE reasoner_runs SET status='completed', records_analyzed=?, output=?, completed_at=?, updated_at=? WHERE id=?",
        rusqlite::params![records, output, now, now, id],
    ).map_err(|e| e.to_string())?;
    Ok(())
}

fn db_fail_run(db: &DbPool, id: &str, error: &str) -> Result<(), String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    let now = chrono::Utc::now().to_rfc3339();
    conn.execute(
        "UPDATE reasoner_runs SET status='failed', error=?, completed_at=?, updated_at=? WHERE id=?",
        rusqlite::params![error, now, now, id],
    ).map_err(|e| e.to_string())?;
    Ok(())
}

fn db_get_run(db: &DbPool, id: &str) -> Result<ReasonerRun, String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    conn.query_row("SELECT * FROM reasoner_runs WHERE id=?", [id], |row| Ok(ReasonerRun::from_row(row)))
        .map_err(|e| e.to_string())
}

fn should_auto_run(db: &DbPool, name: &str, threshold_hours: i64) -> bool {
    let conn = match db.lock() { Ok(c) => c, Err(_) => return false };
    conn.query_row(
        "SELECT completed_at FROM reasoner_runs WHERE reasoner_name=? AND status='completed' ORDER BY completed_at DESC LIMIT 1",
        [name], |row| row.get::<_, String>(0)
    ).map(|last| {
        chrono::DateTime::parse_from_rfc3339(&last)
            .map(|t| chrono::Utc::now().signed_duration_since(t.with_timezone(&chrono::Utc)).num_hours() >= threshold_hours)
            .unwrap_or(true)
    }).unwrap_or(true)
}

#[tauri::command]
pub fn list_reasoner_statuses(db: State<'_, DbPool>) -> Result<Vec<ReasonerStatus>, String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    REASONERS.iter().map(|def| {
        let last_run = conn.query_row(
            "SELECT * FROM reasoner_runs WHERE reasoner_name=? ORDER BY started_at DESC LIMIT 1",
            [def.name], |row| Ok(ReasonerRun::from_row(row))
        ).ok();
        Ok(ReasonerStatus {
            name: def.name.to_string(),
            description: def.description.to_string(),
            schedule: def.schedule.to_string(),
            last_run,
        })
    }).collect()
}

#[tauri::command]
pub fn list_reasoner_runs(name: String, db: State<'_, DbPool>) -> Result<Vec<ReasonerRun>, String> {
    let conn = db.lock().map_err(|e| e.to_string())?;
    let mut stmt = conn.prepare(
        "SELECT * FROM reasoner_runs WHERE reasoner_name=? ORDER BY started_at DESC LIMIT 20"
    ).map_err(|e| e.to_string())?;
    stmt.query_map([&name], |row| Ok(ReasonerRun::from_row(row)))
        .map_err(|e| e.to_string())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn run_reasoner(
    name: String,
    model: String,
    app: AppHandle,
    db: State<'_, DbPool>,
    keys: State<'_, ApiKeyStore>,
) -> Result<ReasonerRun, String> {
    let keys_snap: std::collections::HashMap<String, String> = {
        keys.lock().map_err(|e| e.to_string())?.clone()
    };
    let run_id = db_start_run(&db, &name, &model)?;
    let _ = app.emit("reasoner-started", &run_id);
    match execute_reasoner(&name, &model, &db, &keys_snap).await {
        Ok((records, output)) => {
            db_finish_run(&db, &run_id, records, &output)?;
            let run = db_get_run(&db, &run_id)?;
            let _ = app.emit("reasoner-completed", &run);
            Ok(run)
        }
        Err(err) => {
            db_fail_run(&db, &run_id, &err)?;
            let run = db_get_run(&db, &run_id)?;
            let _ = app.emit("reasoner-completed", &run);
            Err(err)
        }
    }
}
${hasScheduled ? `
async fn run_scheduled_reasoner(app: &AppHandle, db: &DbPool, keys: &std::collections::HashMap<String, String>, name: &str, model: &str) {
    let run_id = match db_start_run(db, name, model) { Ok(id) => id, Err(e) => { eprintln!("[Reasoner] start_run failed: {}", e); return; } };
    let _ = app.emit("reasoner-started", &run_id);
    match execute_reasoner(name, model, db, keys).await {
        Ok((records, output)) => {
            let _ = db_finish_run(db, &run_id, records, &output);
            if let Ok(run) = db_get_run(db, &run_id) { let _ = app.emit("reasoner-completed", run); }
            eprintln!("[Reasoner] {} completed ({} records)", name, records);
        }
        Err(err) => {
            let _ = db_fail_run(db, &run_id, &err);
            eprintln!("[Reasoner] {} failed: {}", name, err);
        }
    }
}

pub fn start_reasoner_scheduler(app: AppHandle, db: crate::db::DbPool, keys: std::sync::Arc<ApiKeyStore>, default_model: String) {
    tokio::spawn(async move {
        tokio::time::sleep(tokio::time::Duration::from_secs(10)).await;
        let keys_snap: std::collections::HashMap<String, String> = match keys.lock() { Ok(k) => k.clone(), Err(_) => return };
${schedulerEntries}
    });
}` : ''}`;
}

// ─── ReasonerView TSX stub ───────────────────────────────────────────────────

export function generateReasonerViewTsx(ast: AgiFile): string {
  if (ast.reasoners.length === 0) return '';

  const reasonerNames = ast.reasoners.map((r) =>
    `  { name: '${r.name}', label: '${r.name.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}', schedule: '${r.schedule}' },`
  ).join('\n');

  return `// ReasonerView — generated by Agicore
// @agicore-protected — customise freely, won't be overwritten on regen

import { useState, useEffect } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { listen } from '@tauri-apps/api/event';

const REASONERS = [
${reasonerNames}
];

interface ReasonerRun {
  id: string; reasonerName: string; status: string;
  recordsAnalyzed: number; output?: string; error?: string;
  startedAt: string; completedAt?: string;
}

export function ReasonerView() {
  const [runs, setRuns] = useState<Record<string, ReasonerRun | null>>({});
  const [running, setRunning] = useState<string | null>(null);

  useEffect(() => {
    REASONERS.forEach(async (r) => {
      const list = await invoke<ReasonerRun[]>('list_reasoner_runs', { name: r.name });
      setRuns(prev => ({ ...prev, [r.name]: list[0] ?? null }));
    });
    const unsub = listen<ReasonerRun>('reasoner-completed', (e) => {
      setRuns(prev => ({ ...prev, [e.payload.reasonerName]: e.payload }));
      setRunning(null);
    });
    return () => { unsub.then(fn => fn()); };
  }, []);

  async function runNow(name: string, model: string) {
    setRunning(name);
    try { await invoke('run_reasoner', { name, model }); }
    catch (e) { console.error(e); setRunning(null); }
  }

  return (
    <div className="p-6 space-y-4">
      <h1 className="text-lg font-semibold">Reasoners</h1>
      {REASONERS.map(r => (
        <div key={r.name} className="border border-slate-700 rounded-lg p-4">
          <div className="flex items-center justify-between mb-2">
            <h2 className="font-medium">{r.label}</h2>
            <button onClick={() => runNow(r.name, 'claude-sonnet-4-6')}
              disabled={running === r.name}
              className="px-3 py-1 text-sm bg-blue-600 hover:bg-blue-500 text-white rounded">
              {running === r.name ? 'Running…' : 'Run Now'}
            </button>
          </div>
          <p className="text-xs text-gray-500 mb-2">Schedule: {r.schedule}</p>
          {runs[r.name]?.output && (
            <pre className="text-xs text-gray-300 whitespace-pre-wrap max-h-40 overflow-y-auto">{runs[r.name]!.output}</pre>
          )}
        </div>
      ))}
    </div>
  );
}
`;
}

// ─── Utility: parse window string to days ─────────────────────────────────────

function parseWindowToDays(window: string): number {
  const match = window.match(/^(\d+)([hdwm])$/);
  if (!match) return 7;
  const n = parseInt(match[1]!);
  switch (match[2]) {
    case 'h': return Math.ceil(n / 24);
    case 'd': return n;
    case 'w': return n * 7;
    case 'm': return n * 30;
    default:  return 7;
  }
}

// ─── Utility: build input query from REASONER input spec ─────────────────────

function buildInputQuery(r: ReasonerDecl, ast: AgiFile): string {
  const channels = r.input.channels;
  const window = r.input.window ?? '7d';
  const filter = r.input.filter;

  // Map channel name → entity table (best-effort: channel name ≈ snake_case entity name)
  const parts = channels.map((channel) => {
    const table = toSnake(channel);
    const whereClause = `created_at > datetime('now', '-{window} days')${filter ? ` AND ${filter}` : ''}`;
    return `SELECT * FROM ${table} WHERE ${whereClause} ORDER BY created_at DESC LIMIT 200`;
  });

  if (parts.length === 1) return parts[0]!;
  return parts.join(' UNION ALL ') + ' LIMIT 300';
}
