// Auto-generated by Agicore — entity field state machine validators

import type { AgiFile, StagesDecl, StagesCondition } from '@agicore/parser';

export function generateStages(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (!ast.stages || ast.stages.length === 0) return files;

  const tsLines: string[] = [
    `// Auto-generated by Agicore — entity field state machine validators`,
    ``,
    `export interface TransitionResult {`,
    `  allowed: boolean;`,
    `  failedConditions: string[];`,
    `}`,
    ``,
  ];

  for (const s of ast.stages) {
    const fnName = `can${s.entity}${capitalize(s.field)}Transition`;

    // Build per-transition validation logic as comments/data
    const transitionData = s.transitions.map(t => ({
      from: t.from,
      to: t.to,
      match: t.match,
      conditions: t.conditions.map(describeCondition),
    }));

    tsLines.push(`// ${s.entity}.${s.field} state machine`);
    tsLines.push(`type ${s.entity}${capitalize(s.field)}Transition = { from: string; to: string; match: 'all' | 'any'; conditions: string[] };`);
    tsLines.push(`export const ${s.entity.toLowerCase()}${capitalize(s.field)}Transitions: ${s.entity}${capitalize(s.field)}Transition[] = ${JSON.stringify(transitionData, null, 2)};`);
    tsLines.push(``);
    tsLines.push(`export function ${fnName}(`);
    tsLines.push(`  from: string,`);
    tsLines.push(`  to: string,`);
    tsLines.push(`  _checkCondition: (description: string) => boolean`);
    tsLines.push(`): TransitionResult {`);
    tsLines.push(`  const transition = ${s.entity.toLowerCase()}${capitalize(s.field)}Transitions.find(`);
    tsLines.push(`    t => t.from === from && t.to === to`);
    tsLines.push(`  );`);
    tsLines.push(`  if (!transition) {`);
    tsLines.push(`    return { allowed: false, failedConditions: [\`No transition defined from "\${from}" to "\${to}"\`] };`);
    tsLines.push(`  }`);
    tsLines.push(`  const failedConditions: string[] = [];`);
    tsLines.push(`  const results = transition.conditions.map(c => {`);
    tsLines.push(`    const passed = _checkCondition(c);`);
    tsLines.push(`    if (!passed) failedConditions.push(c);`);
    tsLines.push(`    return passed;`);
    tsLines.push(`  });`);
    tsLines.push(`  const allowed = transition.match === 'any'`);
    tsLines.push(`    ? results.some(Boolean)`);
    tsLines.push(`    : results.every(Boolean);`);
    tsLines.push(`  return { allowed, failedConditions: allowed ? [] : failedConditions };`);
    tsLines.push(`}`);
    tsLines.push(``);
  }

  files.set('src/lib/stages.ts', tsLines.join('\n'));

  // Generate a human-readable markdown doc for each STAGES block
  for (const s of ast.stages) {
    const lines: string[] = [
      `# ${s.entity}.${s.field} Stage Machine`,
      ``,
      `Auto-generated from Agicore DSL.`,
      ``,
      `## Transitions`,
      ``,
    ];
    for (const t of s.transitions) {
      lines.push(`### "${t.from}" → "${t.to}"`);
      lines.push(``);
      lines.push(`Match mode: **${t.match}** (${t.match === 'any' ? 'any one condition must pass' : 'all conditions must pass'})`);
      lines.push(``);
      lines.push(`Requirements:`);
      for (const c of t.conditions) {
        lines.push(`- ${describeCondition(c)}`);
      }
      lines.push(``);
    }
    files.set(`scaffold/stages/${s.entity.toLowerCase()}_${s.field}.md`, lines.join('\n'));
  }

  return files;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function describeCondition(c: StagesCondition): string {
  switch (c.op) {
    case 'is_not_null': return `${c.entity}.${c.field} is present (not null)`;
    case 'gt': return `${c.entity}.${c.field} > ${c.value}`;
    case 'lt': return `${c.entity}.${c.field} < ${c.value}`;
    case 'gte': return `${c.entity}.${c.field} >= ${c.value}`;
    case 'lte': return `${c.entity}.${c.field} <= ${c.value}`;
    case 'eq': return `${c.entity}.${c.field} = "${c.value}"`;
    case 'count_gte': return `${c.entity} record count >= ${c.count}`;
    case 'count_gte_where': return `${c.entity} count >= ${c.count} where ${c.whereField} = "${c.whereValue}"`;
    default: return `unknown condition`;
  }
}
