// Generates TypeScript fetch-based API client for web target.
// Replaces Tauri invoke() wrappers when TARGET.runtime === 'axum'.

import type { AgiFile, EntityDecl, FieldDef } from '@agicore/parser';

export function generateWebClient(ast: AgiFile): Map<string, string> {
  const files = new Map<string, string>();
  if (!ast.target || ast.target.runtime !== 'axum') return files;

  files.set('frontend/src/api/client.ts', buildBaseClient());

  for (const entity of ast.entities) {
    files.set(`frontend/src/api/${toSnake(entity.name)}.ts`, buildEntityClient(entity));
  }

  return files;
}

function buildBaseClient(): string {
  return `// api/client.ts — generated by Agicore web target
// Base fetch client with auth header injection and error handling.

let authToken: string | null = null;

export function setAuthToken(token: string) {
  authToken = token;
  localStorage.setItem('auth_token', token);
}

export function loadAuthToken() {
  authToken = localStorage.getItem('auth_token');
}

export function clearAuthToken() {
  authToken = null;
  localStorage.removeItem('auth_token');
}

const API_BASE = import.meta.env.VITE_API_URL ?? '';

export async function apiFetch<T>(
  path: string,
  options: RequestInit = {}
): Promise<T> {
  const headers: Record<string, string> = {
    'Content-Type': 'application/json',
    ...(options.headers as Record<string, string> ?? {}),
  };

  if (authToken) {
    headers['Authorization'] = \`Bearer \${authToken}\`;
  }

  const res = await fetch(\`\${API_BASE}\${path}\`, { ...options, headers });

  if (!res.ok) {
    const body = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(body.error ?? \`Request failed: \${res.status}\`);
  }

  if (res.status === 204) return undefined as T;
  return res.json();
}
`;
}

function buildEntityClient(entity: EntityDecl): string {
  const name = entity.name;
  const snake = toSnake(name);
  const crudRaw = entity.crud;
  const crud: string[] = crudRaw === 'full'
    ? ['create', 'read', 'update', 'delete', 'list']
    : (crudRaw as string[]);

  const tsFields = entity.fields.map(f => {
    const optional = !f.modifiers.includes('REQUIRED');
    return `  ${toSnake(f.name)}${optional ? '?' : ''}: ${tsType(f.type)};`;
  }).join('\n');

  const createFields = entity.fields
    .filter(f => !['id', 'created_at', 'updated_at'].includes(toSnake(f.name)))
    .map(f => {
      const optional = !f.modifiers.includes('REQUIRED');
      return `  ${toSnake(f.name)}${optional ? '?' : ''}: ${tsType(f.type)};`;
    }).join('\n');

  let functions = '';

  if (crud.includes('list')) {
    functions += `
export async function list${name}s(params?: { limit?: number; offset?: number }): Promise<${name}[]> {
  const qs = params ? '?' + new URLSearchParams(params as any).toString() : '';
  return apiFetch(\`/api/${snake}s\${qs}\`);
}
`;
  }

  if (crud.includes('read')) {
    functions += `
export async function get${name}(id: string): Promise<${name}> {
  return apiFetch(\`/api/${snake}s/\${id}\`);
}
`;
  }

  if (crud.includes('create')) {
    functions += `
export async function create${name}(data: Create${name}): Promise<${name}> {
  return apiFetch(\`/api/${snake}s\`, { method: 'POST', body: JSON.stringify(data) });
}
`;
  }

  if (crud.includes('update') || crud.includes('edit')) {
    functions += `
export async function update${name}(id: string, data: Partial<Create${name}>): Promise<${name}> {
  return apiFetch(\`/api/${snake}s/\${id}\`, { method: 'PUT', body: JSON.stringify(data) });
}
`;
  }

  if (crud.includes('delete')) {
    functions += `
export async function delete${name}(id: string): Promise<void> {
  return apiFetch(\`/api/${snake}s/\${id}\`, { method: 'DELETE' });
}
`;
  }

  return `// api/${snake}.ts — generated by Agicore web target
import { apiFetch } from './client';

export interface ${name} {
  id: string;
${tsFields}
  created_at: string;
  updated_at: string;
}

export interface Create${name} {
${createFields}
}
${functions}`;
}

function tsType(t: string): string {
  switch (t) {
    case 'string':   return 'string';
    case 'number':   return 'number';
    case 'float':    return 'number';
    case 'bool':     return 'boolean';
    case 'date':     return 'string';
    case 'datetime': return 'string';
    case 'json':     return 'Record<string, unknown>';
    case 'id':       return 'string';
    default:         return 'string';
  }
}

function toSnake(s: string): string {
  return s.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}
