// Mirrors the Rust types in src-tauri/src/types.rs.
// Will be auto-generated by specta once ENTITY codegen lands.

export interface Conversation {
  id: string;
  title: string;
  messageCount: number;
  createdAt: string;
  updatedAt: string;
}

export interface Message {
  id: string;
  conversationId: string;
  role: 'user' | 'assistant';
  content: string;
  createdAt: string;
}

export interface AppStats {
  totalConversations: number;
  totalMessages: number;
  totalUserMessages: number;
  totalAssistantMessages: number;
  memoriesStored: number;
  totalEscapes: number;
}

export interface GameStateInfo {
  layer: number;
  turnCount: number;
  easterEggsFound: number;
  totalEasterEggs: number;
  isWin: boolean;
  winMethod: string | null;
  activePersona: string | null;
}

export interface SendMessageResult {
  message: Message;
  thinkingDelay: number;
  gameState: GameStateInfo;
}
